GH-20 Configuring Lost Pixel
ssagroup/ui-kit pull request #39
Opened 2023-08-16 10:51 UTC by react-developer-ssa-group

[Configuring Lost Pixel](https://github.com/ssagroup/ui-kit/issues/20)

2023-08-16 13:52 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2023-08-16 14:41 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2023-08-16 14:41 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2023-08-16 15:03 UTC, d-ivashchuk commented on .github/workflows/visual_checking.yml
> +
```suggestion
   - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
```

2023-08-16 15:13 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2023-08-17 07:34 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2023-08-17 07:48 UTC, d-ivashchuk commented on packages/core/lostpixel.config.ts
> +    storybookUrl: './storybook-static',
```suggestion
    storybookUrl: './packages/core/storybook-static',
```

2023-08-17 07:53 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2023-08-17 08:02 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 13       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 storybook/widgets-activity--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/7718ac422ca57bedb9c24bdfd7e9d37f66ba4d2c838b696f5e3be96eb9c01070.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/8da7e9ff541743cdd693a04f55c7955cbe3019bab8d47a9fd848609cb6d3a8ec.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/d1b4f5e70bb228f2183316b2166c53ad44f590b3829d533934a932f2d485a7df.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/b4f0b8cb0f10613ffb10a669d2f4cf683bf9a39281ae8f2a7ea2247c0fa4212f.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/762b5b75d21d49f47033b7acf7c136dcbae65d930d5f2941fed7e715b88b0bb3.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/a380a75d2e522fdf057a04dbf87ef44639ddf6f055abf0e368adecb017230e4f.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-nutrients--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/7e079cdd0afc161fd563e02f20cb0d714b262a7dc0eec29493c6ece3c88fc01f.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-planner--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/15b5ec6fa0555fd18812d63e38856a4c811159e2723e6545fe9760406170c0f1.png) |
</details>



<details>
<summary>🟡 storybook/widgets-nav-bar--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/f5124f58b259a5db8226a023687dfbf75691d0ee4d0e5aaa8eda28efe6c6f05a.png) |
</details>



<details>
<summary>🟡 storybook/widgets-progress-info--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/08756ebcbf8b7f906dd2311ce683c6069b10364b76442dad6a88be8f2227a0f1.png) |
</details>



<details>
<summary>🟡 storybook/widgets-steps-counter--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/994b56eba3839059a835a0301a940b6f80ab85c62bde7a910194dc3157a8d016.png) |
</details>



<details>
<summary>🟡 storybook/widgets-upcoming-workouts--upcoming-workouts (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ea6129eda4a1605e9d312c5f17f89b6d29b28e1a08d8c558deb906afc20f6905.png) |
</details>



<details>
<summary>🟡 storybook/widgets-water-consume--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/610106979f4e3e804364570afbc74544b18a0a464ecd38d10b90037a62b262e7.png) |
</details>

2023-08-17 08:28 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 67       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 storybook/components-badge--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d7525bc134e34477ae1083ba894c53558c329962650cc6204f6fea1fb80fde62.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d72091363bd7f106c087f77f6887a098c4b2e6099ebcfa35b9a714f9bed0f2b2.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/2a1c1c2337c270ddd77161082a501c9e8c7d48dd829dd3de052ffac6e8d2fb64.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/0ce758b68fa6fbd1c0f5b2d0f3e9a551a4d1a237e00d052f44436f2ae371fca1.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3a57f2d9136f9a49d33701b3fc8efea574e9518326131e5ecb0cce031559da71.png) |
</details>



<details>
<summary>🟡 storybook/components-button--medium (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/45843ff4fc8eff43f18bde9633800bd5d6e29b9d9e297c30a54cfbbe3320a662.png) |
</details>



<details>
<summary>🟡 storybook/components-button--small (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/2a1c1c2337c270ddd77161082a501c9e8c7d48dd829dd3de052ffac6e8d2fb64.png) |
</details>



<details>
<summary>🟡 storybook/components-button--start-icon (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/97127d6fd25e7a56cfc9003dee6f8cdb0737f12f383b437d03e6327ad1f1a4c2.png) |
</details>



<details>
<summary>🟡 storybook/components-card--basic (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d45480675ba73a52c4f830b75c63f865280cd2b6c8ea3a841fef9a1c582c7f8f.png) |
</details>



<details>
<summary>🟡 storybook/components-card--float-header (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8133d7fe9831b9682324b279f3086aa418a9ef82643153dfd8e9acf2a19849e7.png) |
</details>



<details>
<summary>🟡 storybook/components-card--icon-header (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e963d93305580c005f3d836c1a6e5ed7d4e48a0716c617e6c454f9eb6d06bc16.png) |
</details>



<details>
<summary>🟡 storybook/components-card--item-card (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/157488819a7cb550702fae7c174a83a13f0ede46bfcccea915eac557682cb906.png) |
</details>



<details>
<summary>🟡 storybook/components-card--item-card-action (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/fa653eff24fa07ccc1f94e9251d407cc1d12334fc6e178c57a5c4bb07cfa7493.png) |
</details>



<details>
<summary>🟡 storybook/components-card--item-card-avatar (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/55b7bde12803b63c1b7625e0f9ad16f034c94939282760523b4e22e400da97c6.png) |
</details>



<details>
<summary>🟡 storybook/components-card--no-shadow (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d45480675ba73a52c4f830b75c63f865280cd2b6c8ea3a841fef9a1c582c7f8f.png) |
</details>



<details>
<summary>🟡 storybook/components-checkbox--all-states (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/93826524a1dcf34d9f4003fd39eaf842c40eaa6ab039ce4e5d961faacfe1e558.png) |
</details>



<details>
<summary>🟡 storybook/components-checkbox--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/a15cc3772e1d499c478bc1a2ffd66d1b11e4a4856903a00e19b13ee00ea723fa.png) |
</details>



<details>
<summary>🟡 storybook/components-color-picker--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/bb38f4a7757498696d1802686e7cef193693a5aa98b1c165e7ae2fa6cc978a9a.png) |
</details>



<details>
<summary>🟡 storybook/components-dropdown--basic (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/6cb728157beab80113276e918acf9ae520bbb889212abb829b5f867ea8788dd2.png) |
</details>



<details>
<summary>🟡 storybook/components-dropdown--custom (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/23ea4ab92b2c51be430d5ba54202511841892154e4f00a5991654ad7804a0ad1.png) |
</details>



<details>
<summary>🟡 storybook/components-dropdown--no-items (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3f242f3b3963b51a3a1215c66aada1161dedbebcf2230e5e8bc1f2378c312339.png) |
</details>



<details>
<summary>🟡 storybook/components-dropdown--simple (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3f242f3b3963b51a3a1215c66aada1161dedbebcf2230e5e8bc1f2378c312339.png) |
</details>



<details>
<summary>🟡 storybook/components-icons--icons (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/232abbd708a9c70d4605d715fbd013c08b224f7364cb6335e660a4e8f311bc14.png) |
</details>



<details>
<summary>🟡 storybook/components-inputs--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/611b2744df0941ecc57a1011a0d6f7eb91994d981bc31b1e45da31aadd8aae60.png) |
</details>



<details>
<summary>🟡 storybook/components-inputs--disabled (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/f8148de79ed250c169e4cb132e33064a418580871e2655f9514ea4911e7d24f0.png) |
</details>



<details>
<summary>🟡 storybook/components-inputs--with-call-action (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e46ef36434d2afa43f3cbcd9d63b7452ac76005b3f6cabff702f26150f90fe0f.png) |
</details>



<details>
<summary>🟡 storybook/components-inputs--with-error (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/0df387400ce818a66beadc2c9d1aa1f8febc733e116526d52debb56a414646bd.png) |
</details>



<details>
<summary>🟡 storybook/components-inputs--with-icon (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/f7aff277c6d1fc7c549b2d8b3bd6372be289781c16adf7c07cf82810d3993704.png) |
</details>



<details>
<summary>🟡 storybook/components-inputs--with-sta [...]

2023-08-17 08:28 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 13       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 storybook/widgets-activity--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/c5461d8e3bce8c4fa5a50cd1adc7fd5e80392a04a42c9e6cad8bf34717faaf81.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/8da7e9ff541743cdd693a04f55c7955cbe3019bab8d47a9fd848609cb6d3a8ec.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/d1b4f5e70bb228f2183316b2166c53ad44f590b3829d533934a932f2d485a7df.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/b4f0b8cb0f10613ffb10a669d2f4cf683bf9a39281ae8f2a7ea2247c0fa4212f.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/762b5b75d21d49f47033b7acf7c136dcbae65d930d5f2941fed7e715b88b0bb3.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/a380a75d2e522fdf057a04dbf87ef44639ddf6f055abf0e368adecb017230e4f.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-nutrients--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/9e078a6938a63fb988e27a458fa2acf8d572e6b377222a70757687379ad879c9.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-planner--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/15b5ec6fa0555fd18812d63e38856a4c811159e2723e6545fe9760406170c0f1.png) |
</details>



<details>
<summary>🟡 storybook/widgets-nav-bar--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/f5124f58b259a5db8226a023687dfbf75691d0ee4d0e5aaa8eda28efe6c6f05a.png) |
</details>



<details>
<summary>🟡 storybook/widgets-progress-info--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/08756ebcbf8b7f906dd2311ce683c6069b10364b76442dad6a88be8f2227a0f1.png) |
</details>



<details>
<summary>🟡 storybook/widgets-steps-counter--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/994b56eba3839059a835a0301a940b6f80ab85c62bde7a910194dc3157a8d016.png) |
</details>



<details>
<summary>🟡 storybook/widgets-upcoming-workouts--upcoming-workouts (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ea6129eda4a1605e9d312c5f17f89b6d29b28e1a08d8c558deb906afc20f6905.png) |
</details>



<details>
<summary>🟡 storybook/widgets-water-consume--default (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/610106979f4e3e804364570afbc74544b18a0a464ecd38d10b90037a62b262e7.png) |
</details>

2023-08-17 10:29 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2023-08-17 10:30 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 2  | ❗       |
    


*❗ storybook/widgets-activity--default*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/c5461d8e3bce8c4fa5a50cd1adc7fd5e80392a04a42c9e6cad8bf34717faaf81.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/f7757e1819f2ef6acdbd5dff718a4eaa559d56dec01cb80f175f668e9072caba.png) |



*❗ storybook/widgets-meal-nutrients--default*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/9e078a6938a63fb988e27a458fa2acf8d572e6b377222a70757687379ad879c9.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/3a49aa0751f78b2042164e11232cd61aa15cc2121b4051467be56158fe0bcc60.png) |

2023-08-18 16:15 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 15       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 3  | ❗       |
    


<details>
<summary>🟡 storybook/components-badge--all-states (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/f7461b02a5101adbc8a78463e06cdd8b11c9c6b0156c0cdc63eb50712baad2f5.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/51b3baa6fc88efe871760f1138bede140f0644dc4de06d305de4ed8271412c94.png) |
</details>



<details>
<summary>🟡 storybook/components-button--secondary (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8885206f30d52b5014655bd48fb410fda61510ea8428ab7d2630e5fd97846eee.png) |
</details>



<details>
<summary>🟡 storybook/components-button--tertiary (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b2cf11a0020c306387b47a2ee872b76eabdfed13d638aeedc19eaff4d3cd626a.png) |
</details>



<details>
<summary>🟡 storybook/components-color-picker--setted-color (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/65dddee8eec59f29074934d2bbf05b77472364cf224949ecb7eea66c96a629d0.png) |
</details>



<details>
<summary>🟡 storybook/components-dropdown--opened (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/7ac61e8a85ffa88a0e0f3a4518a4cfdcb186df6e2c51100bd8683c55959895da.png) |
</details>



<details>
<summary>🟡 storybook/components-modal--opened (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/9f8f2dcccfcc24118ca299c12d8a8df8249b911863b2ff2f261b6f7413961e28.png) |
</details>



<details>
<summary>🟡 storybook/components-progress-circle--sizes-and-colors (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/ef653e81ae0d148b8bce888e904f3335e501d2ed49bef73ad81a888ec8a7cf1a.png) |
</details>



<details>
<summary>🟡 storybook/components-switch--focused (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/661184698da0aab01a64012662b38749e97a7caf2940541022d39a094c4adc4b.png) |
</details>



<details>
<summary>🟡 storybook/components-tab-bar--time-period-tab-bar-active-tab (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e744adefa376bd574f1d0af6bcba00c5c03e76723df3e790e5889b8a466a5c88.png) |
</details>



<details>
<summary>🟡 storybook/components-tab-bar--week-tab-bar-active-tab (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/fef8c0e8a9dfcb970cfe6b1ffae9676eb7b12bbfc6d10c9152a7aee75cd384ad.png) |
</details>



<details>
<summary>🟡 storybook/components-tag--all-states (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8f354be1a9b5c2fd11417d58cde858e78f951ce54986716f753f3c318752c584.png) |
</details>



<details>
<summary>🟡 storybook/components-text-field--focused (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d8d8737b1ada70267c3d4913966c47c256ada7a11fb9da9774d7d6272a8c72d7.png) |
</details>



<details>
<summary>🟡 storybook/components-textarea--focused (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d53260a6b2b44dae39aab0bedf6eb7a0289bac3b2caf4c2e535b8da798de5e21.png) |
</details>



<details>
<summary>🟡 storybook/components-tooltip--opened (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5b7875b3e0127562df12ca5158d902129631ad589586dd89ff79254f57e751ac.png) |
</details>



*❗ storybook/components-radio-buttons-radio--radio*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/9e6ecfcc14c54c636b52bac2fb5e7d463189b9bb4437affd014bc6702308916c.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3404dab0678c8a863607f8cc8b9f80a248a34f63f9484fd30d54e66b5b0fc04d.png) |



*❗ storybook/components-switch--default*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/60d0d69037e1feeb1820cbc8ef9f6425551a2988797cdb835c42ae80d080552c.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/aff050344cec1c3305171f2b794372956ab3debea7daf7cd41362121c67043df.png) |



*❗ storybook/components-tag--default*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8dabd40d429242b4dc7341ae9a24fe6c91978d004f0645046494b2290b9717b3.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dc672dd7ee4995d7319657f0a0bb7aa4bd6048b16c9e7856426c0f156afa067c.png) |

2023-08-18 16:15 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 2  | ❗       |
    


*❗ storybook/widgets-activity--default*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/f7757e1819f2ef6acdbd5dff718a4eaa559d56dec01cb80f175f668e9072caba.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/4722131225a59adbb33fce9781f552bac4544bb9c7069e0a72a5a28c75c9d935.png) |



*❗ storybook/widgets-meal-nutrients--default*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/3a49aa0751f78b2042164e11232cd61aa15cc2121b4051467be56158fe0bcc60.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/0dbf1d4ecdbfad122f61da3770d30c82c977fa6fde2c1c56a7b6223732340e47.png) |

2023-08-21 07:33 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 15       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 3  | ❗       |
    


<details>
<summary>🟡 storybook/components-badge--all-states (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/f7461b02a5101adbc8a78463e06cdd8b11c9c6b0156c0cdc63eb50712baad2f5.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/51b3baa6fc88efe871760f1138bede140f0644dc4de06d305de4ed8271412c94.png) |
</details>



<details>
<summary>🟡 storybook/components-button--secondary (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8885206f30d52b5014655bd48fb410fda61510ea8428ab7d2630e5fd97846eee.png) |
</details>



<details>
<summary>🟡 storybook/components-button--tertiary (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b2cf11a0020c306387b47a2ee872b76eabdfed13d638aeedc19eaff4d3cd626a.png) |
</details>



<details>
<summary>🟡 storybook/components-color-picker--setted-color (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/65dddee8eec59f29074934d2bbf05b77472364cf224949ecb7eea66c96a629d0.png) |
</details>



<details>
<summary>🟡 storybook/components-dropdown--opened (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/7ac61e8a85ffa88a0e0f3a4518a4cfdcb186df6e2c51100bd8683c55959895da.png) |
</details>



<details>
<summary>🟡 storybook/components-modal--opened (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/9f8f2dcccfcc24118ca299c12d8a8df8249b911863b2ff2f261b6f7413961e28.png) |
</details>



<details>
<summary>🟡 storybook/components-progress-circle--sizes-and-colors (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/ef653e81ae0d148b8bce888e904f3335e501d2ed49bef73ad81a888ec8a7cf1a.png) |
</details>



<details>
<summary>🟡 storybook/components-switch--focused (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/661184698da0aab01a64012662b38749e97a7caf2940541022d39a094c4adc4b.png) |
</details>



<details>
<summary>🟡 storybook/components-tab-bar--time-period-tab-bar-active-tab (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e744adefa376bd574f1d0af6bcba00c5c03e76723df3e790e5889b8a466a5c88.png) |
</details>



<details>
<summary>🟡 storybook/components-tab-bar--week-tab-bar-active-tab (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b92b2e218e6218594713bb4d057709b4347383bf894b4def4da9cb34379c6770.png) |
</details>



<details>
<summary>🟡 storybook/components-tag--all-states (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8f354be1a9b5c2fd11417d58cde858e78f951ce54986716f753f3c318752c584.png) |
</details>



<details>
<summary>🟡 storybook/components-text-field--focused (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d8d8737b1ada70267c3d4913966c47c256ada7a11fb9da9774d7d6272a8c72d7.png) |
</details>



<details>
<summary>🟡 storybook/components-textarea--focused (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d53260a6b2b44dae39aab0bedf6eb7a0289bac3b2caf4c2e535b8da798de5e21.png) |
</details>



<details>
<summary>🟡 storybook/components-tooltip--opened (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5b7875b3e0127562df12ca5158d902129631ad589586dd89ff79254f57e751ac.png) |
</details>



*❗ storybook/components-radio-buttons-radio--radio*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/9e6ecfcc14c54c636b52bac2fb5e7d463189b9bb4437affd014bc6702308916c.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3404dab0678c8a863607f8cc8b9f80a248a34f63f9484fd30d54e66b5b0fc04d.png) |



*❗ storybook/components-switch--default*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/60d0d69037e1feeb1820cbc8ef9f6425551a2988797cdb835c42ae80d080552c.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/aff050344cec1c3305171f2b794372956ab3debea7daf7cd41362121c67043df.png) |



*❗ storybook/components-tag--default*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8dabd40d429242b4dc7341ae9a24fe6c91978d004f0645046494b2290b9717b3.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dc672dd7ee4995d7319657f0a0bb7aa4bd6048b16c9e7856426c0f156afa067c.png) |

2023-08-21 07:35 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 2       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 3  | ❗       |
    


*🟡 storybook/widgets-nav-bar--visible-by-default-on-mobile*: 


| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/9f2075736ab2c3c1b484e20dbac36eacd9dbbcbf792e4d74a3beef900427df32.png) |



*🟡 storybook/widgets-nav-bar--wide-screen*: 


| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/f5124f58b259a5db8226a023687dfbf75691d0ee4d0e5aaa8eda28efe6c6f05a.png) |



*❗ storybook/widgets-activity--default*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/f7757e1819f2ef6acdbd5dff718a4eaa559d56dec01cb80f175f668e9072caba.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/4722131225a59adbb33fce9781f552bac4544bb9c7069e0a72a5a28c75c9d935.png) |



*❗ storybook/widgets-meal-nutrients--default*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/3a49aa0751f78b2042164e11232cd61aa15cc2121b4051467be56158fe0bcc60.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/41d87243319d69283a0ee836cd89ffb76aad2f9d8a1fc5f01bf3f9b9806e603b.png) |



*❗ storybook/widgets-meal-planner--default*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/15b5ec6fa0555fd18812d63e38856a4c811159e2723e6545fe9760406170c0f1.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/68ac422ed6027fdea9a95d80d2eeb7b3290665f10277e9f23c5a9aee0b02f4e4.png) |

2023-08-21 09:03 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 15       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 3  | ❗       |
    


<details>
<summary>🟡 storybook/components-badge--all-states (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dad9aa459f30e87d735ca1658e0d6cf1b7fceae18c6b94f68b4f35fb1bcd01f5.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/51b3baa6fc88efe871760f1138bede140f0644dc4de06d305de4ed8271412c94.png) |
</details>



<details>
<summary>🟡 storybook/components-button--secondary (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8885206f30d52b5014655bd48fb410fda61510ea8428ab7d2630e5fd97846eee.png) |
</details>



<details>
<summary>🟡 storybook/components-button--tertiary (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b2cf11a0020c306387b47a2ee872b76eabdfed13d638aeedc19eaff4d3cd626a.png) |
</details>



<details>
<summary>🟡 storybook/components-color-picker--setted-color (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/65dddee8eec59f29074934d2bbf05b77472364cf224949ecb7eea66c96a629d0.png) |
</details>



<details>
<summary>🟡 storybook/components-dropdown--opened (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/7ac61e8a85ffa88a0e0f3a4518a4cfdcb186df6e2c51100bd8683c55959895da.png) |
</details>



<details>
<summary>🟡 storybook/components-modal--opened (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/9f8f2dcccfcc24118ca299c12d8a8df8249b911863b2ff2f261b6f7413961e28.png) |
</details>



<details>
<summary>🟡 storybook/components-progress-circle--sizes-and-colors (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/ef653e81ae0d148b8bce888e904f3335e501d2ed49bef73ad81a888ec8a7cf1a.png) |
</details>



<details>
<summary>🟡 storybook/components-switch--focused (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/661184698da0aab01a64012662b38749e97a7caf2940541022d39a094c4adc4b.png) |
</details>



<details>
<summary>🟡 storybook/components-tab-bar--time-period-tab-bar-active-tab (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b1779e22155ea90b83b60f57c4a864ced4740301d5066ee78d8fe06e7d344c0d.png) |
</details>



<details>
<summary>🟡 storybook/components-tab-bar--week-tab-bar-active-tab (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b92b2e218e6218594713bb4d057709b4347383bf894b4def4da9cb34379c6770.png) |
</details>



<details>
<summary>🟡 storybook/components-tag--all-states (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/fac90e1ba800933afcb67bfd43efc6c6808250243434f241d9f13d7e71d0f384.png) |
</details>



<details>
<summary>🟡 storybook/components-text-field--focused (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/76810c8e943bacd184fc5efe95add484364193fc0d0afb88cc0a767610714278.png) |
</details>



<details>
<summary>🟡 storybook/components-textarea--focused (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d53260a6b2b44dae39aab0bedf6eb7a0289bac3b2caf4c2e535b8da798de5e21.png) |
</details>



<details>
<summary>🟡 storybook/components-tooltip--opened (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/76ef61aa914352fbb00b57194e6ff3cd1cae0b054ff8585a40663f011cf8bbf9.png) |
</details>



*❗ storybook/components-radio-buttons-radio--radio*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/9e6ecfcc14c54c636b52bac2fb5e7d463189b9bb4437affd014bc6702308916c.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3404dab0678c8a863607f8cc8b9f80a248a34f63f9484fd30d54e66b5b0fc04d.png) |



*❗ storybook/components-switch--default*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/60d0d69037e1feeb1820cbc8ef9f6425551a2988797cdb835c42ae80d080552c.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/aff050344cec1c3305171f2b794372956ab3debea7daf7cd41362121c67043df.png) |



*❗ storybook/components-tag--default*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8dabd40d429242b4dc7341ae9a24fe6c91978d004f0645046494b2290b9717b3.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dc672dd7ee4995d7319657f0a0bb7aa4bd6048b16c9e7856426c0f156afa067c.png) |

2023-08-21 09:04 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 30       | 🟡       |
| Deleted         | 13     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 storybook/widgets-activity--default__[w1024px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/122cf16109b4ae85dd222227b9f266490bb8b8528842af4b2369281f8e3b87f7.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/364f8a3bc78d2018533fbc3bd185e75161a2156d4608e3e8e7c392660767e033.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1024px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/7e6cfd19c174ba402df2dd6db96295367025d6ef10dce79c48a08bc132fa15fe.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ade614c1048e433ce8bfed2767e6184b0b283808b3fbdf12e9bea05fefca271d.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1024px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/e3470111b63bbdc54415fb2a64d0b4e6be7072cae1f5c0697351801bcf47bd60.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/05615ebf25d05bb37d830395423ddd29d64fce07302effbbff422a360730cbd0.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1024px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/48ebcd2b36f0049b8f4f964c352bfe729ef976a2d96687a2373f8f3011eb22cf.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/745e6382cef9ccfec1963862bcf0e003991492e9d34210862fec4979b0e37a52.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w1024px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/d66a90607fe4f31227cff09b6aa0d2f0e0e0421a6aff3196310d1dfd7477a5a3.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/3dc5b33edf9f79dfb249d3c1b552504967c9c5c534538eaa832d00093b19bd0c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w1024px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/aef651acfb7160afaf84431b2a2d756e39dbc1187987f3b96b1cb7e4e3c40447.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ed42f96b3639546ad215b798c3c65d6f67d6abcc7fe4c03532ab99cb5bcdd385.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-nutrients--default__[w1024px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/9fd1f35dfa78edf738e7bfa3b68614800c6d7bb0baae15eb5da9e8a6081a168f.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-nutrients--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/b3c870536b380fba5bd07f2efd65852b22b263978cd689988bf65401dfcab25b.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-planner--default__[w1024px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/d1f7816d193d9d2118cb60a61f7301ee3fb4084a6c12a1862154881672859490.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-planner--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/82b9de2919450b2afef425aa4ed93f09205fdb14715d292faef02e203dbe4adc.png) |
</details>



<details>
<summary>🟡 storybook/widgets-nav-bar--default__[w1024px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/37c0abf951fc8057e0b99e234687b92fb311ec1026d00caeb7b2843ee8d66946.png) |
</details>



<details>
<summary>🟡 storybook/widgets-nav-bar--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/6a28f24cda9152f81a7de8086266d77cfb93f63528d2f2a7a3f3fdee7b244458.png) |
</details>



<details>
<summary>🟡 storybook/widgets-nav-bar--visible-by-default-on-mobile__[w1024px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/551cc3070d3ecacef4317d41a733e3e5d5e474663bcb2954895b6129806aa063.png) |
</details>



<details>
<summary>🟡 storybook/widgets-nav-bar--visible-by-default-on-mobile__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/6a28f24cda9152f81a7de8086266d77cfb93f63528d2f2a7a3f3fdee7b244458.png) |
</details>



<details>
<summary>🟡 storybook/widgets-nav-bar--wide-screen__[w1024px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/37c0abf951fc8057e0b99e234687b92fb311ec1026d00caeb7b2843ee8d66946.png) |
</details>



<details>
<summary>🟡 storybook/widgets-nav-bar--wide-screen__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/6a28f24cda9152f81a7de8086266d77cfb93f63528d2f2a7a3f3fdee7b244458.png) |
</details>



<details>
<summary>🟡 storybook/widgets-progress-info--default__[w1024px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/4dd1b1f8149bd0d2aedbac1488d7730663205b1a516f26743e9286f18e40a3f7.png) |
</details>



<details>
<summary>🟡 storybook/widgets-progress-info--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/3a6b4f1eb7794539d457836b172e4da0d843b45121a1e45167005cbc33e47ac6.png) |
</details>



<details>
<summary>🟡 storybook/widgets-steps-counter--default__[w1024px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/f71b6b2794da179f3e16b2ce2b9768b4952289aa44257a46cb6ac2329f29818b.png) |
</details>



<details>
<summary>🟡 storybook/widgets-steps-counter--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/c7b30bd5d6d8b61562502a6f1856571e3b5c55e7d21aa231b7f880a6141f05eb.png) |
</details>



<details>
<summary>🟡 storybook/widgets-upcoming-workouts--upcoming-workouts__[w1024px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/dfce55cd7c5613b820ad0a88c90d20ca4f9c40f91965135624699b6cb4046cfc.png) |
</d [...]

2023-08-21 10:44 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 15       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 3  | ❗       |
    


<details>
<summary>🟡 storybook/components-badge--all-states (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dad9aa459f30e87d735ca1658e0d6cf1b7fceae18c6b94f68b4f35fb1bcd01f5.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/51b3baa6fc88efe871760f1138bede140f0644dc4de06d305de4ed8271412c94.png) |
</details>



<details>
<summary>🟡 storybook/components-button--secondary (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8885206f30d52b5014655bd48fb410fda61510ea8428ab7d2630e5fd97846eee.png) |
</details>



<details>
<summary>🟡 storybook/components-button--tertiary (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b2cf11a0020c306387b47a2ee872b76eabdfed13d638aeedc19eaff4d3cd626a.png) |
</details>



<details>
<summary>🟡 storybook/components-color-picker--setted-color (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/65dddee8eec59f29074934d2bbf05b77472364cf224949ecb7eea66c96a629d0.png) |
</details>



<details>
<summary>🟡 storybook/components-dropdown--opened (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/7ac61e8a85ffa88a0e0f3a4518a4cfdcb186df6e2c51100bd8683c55959895da.png) |
</details>



<details>
<summary>🟡 storybook/components-modal--opened (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/9f8f2dcccfcc24118ca299c12d8a8df8249b911863b2ff2f261b6f7413961e28.png) |
</details>



<details>
<summary>🟡 storybook/components-progress-circle--sizes-and-colors (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/ef653e81ae0d148b8bce888e904f3335e501d2ed49bef73ad81a888ec8a7cf1a.png) |
</details>



<details>
<summary>🟡 storybook/components-switch--focused (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/661184698da0aab01a64012662b38749e97a7caf2940541022d39a094c4adc4b.png) |
</details>



<details>
<summary>🟡 storybook/components-tab-bar--time-period-tab-bar-active-tab (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b1779e22155ea90b83b60f57c4a864ced4740301d5066ee78d8fe06e7d344c0d.png) |
</details>



<details>
<summary>🟡 storybook/components-tab-bar--week-tab-bar-active-tab (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b92b2e218e6218594713bb4d057709b4347383bf894b4def4da9cb34379c6770.png) |
</details>



<details>
<summary>🟡 storybook/components-tag--all-states (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/fac90e1ba800933afcb67bfd43efc6c6808250243434f241d9f13d7e71d0f384.png) |
</details>



<details>
<summary>🟡 storybook/components-text-field--focused (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/76810c8e943bacd184fc5efe95add484364193fc0d0afb88cc0a767610714278.png) |
</details>



<details>
<summary>🟡 storybook/components-textarea--focused (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d53260a6b2b44dae39aab0bedf6eb7a0289bac3b2caf4c2e535b8da798de5e21.png) |
</details>



<details>
<summary>🟡 storybook/components-tooltip--opened (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/76ef61aa914352fbb00b57194e6ff3cd1cae0b054ff8585a40663f011cf8bbf9.png) |
</details>



*❗ storybook/components-radio-buttons-radio--radio*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/9e6ecfcc14c54c636b52bac2fb5e7d463189b9bb4437affd014bc6702308916c.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3404dab0678c8a863607f8cc8b9f80a248a34f63f9484fd30d54e66b5b0fc04d.png) |



*❗ storybook/components-switch--default*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/60d0d69037e1feeb1820cbc8ef9f6425551a2988797cdb835c42ae80d080552c.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/aff050344cec1c3305171f2b794372956ab3debea7daf7cd41362121c67043df.png) |



*❗ storybook/components-tag--default*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8dabd40d429242b4dc7341ae9a24fe6c91978d004f0645046494b2290b9717b3.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dc672dd7ee4995d7319657f0a0bb7aa4bd6048b16c9e7856426c0f156afa067c.png) |

2023-08-21 10:46 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 60       | 🟡       |
| Deleted         | 13     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 storybook/widgets-activity--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/364f8a3bc78d2018533fbc3bd185e75161a2156d4608e3e8e7c392660767e033.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/a16913294cb25ddef1b768569113e32b9d6177378994a97ad73e4ce28d68569c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/eacc0afb719bda9fdd825b393028b4aad98ada9e6fc19247d1ae8ae89a7adbc0.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/9eb25204ce92c443fc34696414dd9c98aa12f32f6cdcd0aab8d2b6e7f16ce15d.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ade614c1048e433ce8bfed2767e6184b0b283808b3fbdf12e9bea05fefca271d.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/5db407794669215f0f2b44d3c43440b3b0f9f0e99f788be62f9389c86d02dc38.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/57a82819b7cc52d39703ec91a6f1a83bc3ed87de6a98a2a19999066d7552f72e.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/b2230557346940d6b23d2c3c8cf4f257300156a8fdcb33de917d7c6281598880.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/05615ebf25d05bb37d830395423ddd29d64fce07302effbbff422a360730cbd0.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/2b1394982432822a6328ee7cdecb609b5b9ccb4cf9b66893ecbdb3b4eb7d0aa9.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/704433b0bda358b4b6d4f0b2ba72f474014e1570ded4bc44e56821ac1765ad8c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/addd02c234e94611af1c6552ebf693efc7c633a104b6a34d797a44e637fb8fe6.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/745e6382cef9ccfec1963862bcf0e003991492e9d34210862fec4979b0e37a52.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/11b0a68507b2211c4d237a0e7f50add0115b16e6dbd78030d7e3e3f4c19641fa.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/f952ab0219b9b90657e3b9b07f27af343524f34a5267cc64e9747d76115322f7.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/c32eb553e19d3c902b3b065d05cd69c135de68c699da016f5c8a0b4925530ead.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/3dc5b33edf9f79dfb249d3c1b552504967c9c5c534538eaa832d00093b19bd0c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ae0f5420802637138eaa3e72470dfe8bd2d670053e074b56b351439b946379c1.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/e8ef0e338deccfdbe6fb0b11dbe78fe7cc305512cb8937aa4425d1546b1d6f64.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/4fd13dc2c9f494620b2c9538cd8704f25a025472bf44ca041854db2dd7b789c7.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ed42f96b3639546ad215b798c3c65d6f67d6abcc7fe4c03532ab99cb5bcdd385.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/5cf20c5cf9a56fb93edfb9ab5a61e243bf50ee2fd62beb0b8d6f36b66509fef9.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/a12f25a01253108989eb986159962003eb0319f61e8f77fe3b2d76993068e1b2.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/1d4dc9f9fff32ae1743636a7cadc078d27e80e3b37020e793552923be7fef600.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-nutrients--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ace915f33b58b7c7e8da040b2645c2b9f216bb60d6eaa36239f5f1e47e758794.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-nutrients--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/0a97276f8f914bd993a537e433ac470f496be735fdfc50e3aeb2e15f145a14b6.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-nutrients--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/c641c6f8a9b1e858e829619ef777b932a52f64d1e207f078a09fb3fa311f43bb.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-nutrients--default__[w900px] (cli [...]

2023-08-21 11:00 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 328       | 🟡       |
| Deleted         | 67     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 storybook/components-badge--all-states__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dea13e5c593e1a90c1759f8ecaf10b6c017b14e507a0422e0f122eb0dfc07c5c.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8b696718c79554103bca8de05c7a6d1015027c3b6d269813fa7fec913d48ff6e.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/029bc7108c40f833d3d78548eea1c4164d9fcdeaba58c5ddf4f7b4b5b8f6e3de.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dfe4ec2afb1ed1902a16cc2b087bd5de6fad1b35ae8d6eee768565c0ca2ccd90.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/11a51c87621aa923dc73e620d187a1f7dc7862dc315eb60c82c7efb81da90521.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1e7ae0e871ec9854e82b28b8dd2d2dbd25f597b6982ab5a8bc14607b72847fe7.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e53b26b7e5c0de6dacf7d330bc50c7375ac2960c361981ade0e1304e8cd760b6.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/77f06365fd72e7b85652aed060d8602b18ebc67ccf821f035aa76f7ffbf26cbe.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/7aba7db1dbefe46796980d8f718e6bea9c4237a8dc06ee71984431800398064c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5968e6a597503cbb177d052b2f065263282332e8251c8663694e900498918336.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1ac83021779e4c153b77f8ca5dd7939da55772a60d4f11cceb4dd6f15f599dca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e839dc541b4ce9c373b891275614436b21e7b1bc1ae35bea2e8cf39d281f3ba7.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3f1f35e34c5f80f8d005ffecd433a6f8b6de281daf3ad99b22bd931f4ab1503f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b43bcbba8f2e53f6176e263c503c448ce6fcd21dcf29bec7073ac7d8cb746298.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c49830474274889076bcd7e9dfc4b4add919cdf8c1443055af6db2b3ba8b946c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/ce09f0107914e2bafb4a82a9b6e9915e7ac94c9625e04a02fbcc53219ed770c0.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/98d9ddd4368146d21c791bca1020b32c8d369244d3c34f8fdf9f36047a340700.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3b1d0557477ab9e38b391ccb9cf24e2ed5bd6bd9049aca99c820c8e685888c71.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/fad419a34aa3a1fa18d689ddb55ad02f6602dc7f03b7c35e391e2f8491f6c5ca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d16653698068f9d3c28ea4295fe5569b598ebde3a2e9cfc7b47765a824f1faf6.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/33e6db51c7c7a961958186128f10c7eedaa354c3bf90d005abd9e53686508f7f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dc28afd48376cd64fe9fe85a953f5a53dca742730caa2d447cb8266cf1264318.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5c6c61af89d6fac785ce48a4658617e234a9e84faebdaa94d8d8b891364b0e93.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/81c71a755ffd16e4bc67911eb880c48f2285d117e973f9865bb3f7d4a02a5c79.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dada1a81bd4f99e5950ffe22115fdad9c40cc164207c8d2adc04ff31abb8f025.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c406967a4bb1016152b592443c1323bf8fa07c9b3df38d1a84861fa230fe6211.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/36f72ca78c9b76d12d07fbfafa77d3593c4219712a1846e0f7d5c2bb673804ce.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w900px] (click to expand)</summary> [...]

2023-08-21 11:02 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 60       | 🟡       |
| Deleted         | 13     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 storybook/widgets-activity--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/364f8a3bc78d2018533fbc3bd185e75161a2156d4608e3e8e7c392660767e033.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/a16913294cb25ddef1b768569113e32b9d6177378994a97ad73e4ce28d68569c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/eacc0afb719bda9fdd825b393028b4aad98ada9e6fc19247d1ae8ae89a7adbc0.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/9eb25204ce92c443fc34696414dd9c98aa12f32f6cdcd0aab8d2b6e7f16ce15d.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ade614c1048e433ce8bfed2767e6184b0b283808b3fbdf12e9bea05fefca271d.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/5db407794669215f0f2b44d3c43440b3b0f9f0e99f788be62f9389c86d02dc38.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/57a82819b7cc52d39703ec91a6f1a83bc3ed87de6a98a2a19999066d7552f72e.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/b2230557346940d6b23d2c3c8cf4f257300156a8fdcb33de917d7c6281598880.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/05615ebf25d05bb37d830395423ddd29d64fce07302effbbff422a360730cbd0.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/2b1394982432822a6328ee7cdecb609b5b9ccb4cf9b66893ecbdb3b4eb7d0aa9.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/704433b0bda358b4b6d4f0b2ba72f474014e1570ded4bc44e56821ac1765ad8c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/addd02c234e94611af1c6552ebf693efc7c633a104b6a34d797a44e637fb8fe6.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/745e6382cef9ccfec1963862bcf0e003991492e9d34210862fec4979b0e37a52.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/11b0a68507b2211c4d237a0e7f50add0115b16e6dbd78030d7e3e3f4c19641fa.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/f952ab0219b9b90657e3b9b07f27af343524f34a5267cc64e9747d76115322f7.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/c32eb553e19d3c902b3b065d05cd69c135de68c699da016f5c8a0b4925530ead.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/3dc5b33edf9f79dfb249d3c1b552504967c9c5c534538eaa832d00093b19bd0c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ae0f5420802637138eaa3e72470dfe8bd2d670053e074b56b351439b946379c1.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/e8ef0e338deccfdbe6fb0b11dbe78fe7cc305512cb8937aa4425d1546b1d6f64.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/4fd13dc2c9f494620b2c9538cd8704f25a025472bf44ca041854db2dd7b789c7.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ed42f96b3639546ad215b798c3c65d6f67d6abcc7fe4c03532ab99cb5bcdd385.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/5cf20c5cf9a56fb93edfb9ab5a61e243bf50ee2fd62beb0b8d6f36b66509fef9.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/a12f25a01253108989eb986159962003eb0319f61e8f77fe3b2d76993068e1b2.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/1d4dc9f9fff32ae1743636a7cadc078d27e80e3b37020e793552923be7fef600.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-nutrients--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/b5e7069c9f955164731adbb540681fff45f216edd20843b127fa787b04cdd6f5.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-nutrients--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/240ec669769ea6e78c8466f6ae54ee377b9f75ac5494df472bbc95857bda40cf.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-nutrients--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/2d2125ca0d38ecd80d33f54ca521b460d293533cd1d1b4bcbc5b31651786bd36.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-nutrients--default__[w900px] (cli [...]

2023-08-21 11:40 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 328       | 🟡       |
| Deleted         | 67     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 storybook/components-badge--all-states__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dea13e5c593e1a90c1759f8ecaf10b6c017b14e507a0422e0f122eb0dfc07c5c.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8b696718c79554103bca8de05c7a6d1015027c3b6d269813fa7fec913d48ff6e.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/029bc7108c40f833d3d78548eea1c4164d9fcdeaba58c5ddf4f7b4b5b8f6e3de.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dfe4ec2afb1ed1902a16cc2b087bd5de6fad1b35ae8d6eee768565c0ca2ccd90.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/11a51c87621aa923dc73e620d187a1f7dc7862dc315eb60c82c7efb81da90521.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1e7ae0e871ec9854e82b28b8dd2d2dbd25f597b6982ab5a8bc14607b72847fe7.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e53b26b7e5c0de6dacf7d330bc50c7375ac2960c361981ade0e1304e8cd760b6.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/77f06365fd72e7b85652aed060d8602b18ebc67ccf821f035aa76f7ffbf26cbe.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/7aba7db1dbefe46796980d8f718e6bea9c4237a8dc06ee71984431800398064c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5968e6a597503cbb177d052b2f065263282332e8251c8663694e900498918336.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1ac83021779e4c153b77f8ca5dd7939da55772a60d4f11cceb4dd6f15f599dca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e839dc541b4ce9c373b891275614436b21e7b1bc1ae35bea2e8cf39d281f3ba7.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3f1f35e34c5f80f8d005ffecd433a6f8b6de281daf3ad99b22bd931f4ab1503f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b43bcbba8f2e53f6176e263c503c448ce6fcd21dcf29bec7073ac7d8cb746298.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c49830474274889076bcd7e9dfc4b4add919cdf8c1443055af6db2b3ba8b946c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/ce09f0107914e2bafb4a82a9b6e9915e7ac94c9625e04a02fbcc53219ed770c0.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/98d9ddd4368146d21c791bca1020b32c8d369244d3c34f8fdf9f36047a340700.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3b1d0557477ab9e38b391ccb9cf24e2ed5bd6bd9049aca99c820c8e685888c71.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/fad419a34aa3a1fa18d689ddb55ad02f6602dc7f03b7c35e391e2f8491f6c5ca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d16653698068f9d3c28ea4295fe5569b598ebde3a2e9cfc7b47765a824f1faf6.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/33e6db51c7c7a961958186128f10c7eedaa354c3bf90d005abd9e53686508f7f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dc28afd48376cd64fe9fe85a953f5a53dca742730caa2d447cb8266cf1264318.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5c6c61af89d6fac785ce48a4658617e234a9e84faebdaa94d8d8b891364b0e93.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/81c71a755ffd16e4bc67911eb880c48f2285d117e973f9865bb3f7d4a02a5c79.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dada1a81bd4f99e5950ffe22115fdad9c40cc164207c8d2adc04ff31abb8f025.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c406967a4bb1016152b592443c1323bf8fa07c9b3df38d1a84861fa230fe6211.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/36f72ca78c9b76d12d07fbfafa77d3593c4219712a1846e0f7d5c2bb673804ce.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w900px] (click to expand)</summary> [...]

2023-08-21 11:41 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 60       | 🟡       |
| Deleted         | 13     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 storybook/widgets-activity--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/364f8a3bc78d2018533fbc3bd185e75161a2156d4608e3e8e7c392660767e033.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/a16913294cb25ddef1b768569113e32b9d6177378994a97ad73e4ce28d68569c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/eacc0afb719bda9fdd825b393028b4aad98ada9e6fc19247d1ae8ae89a7adbc0.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/9eb25204ce92c443fc34696414dd9c98aa12f32f6cdcd0aab8d2b6e7f16ce15d.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ade614c1048e433ce8bfed2767e6184b0b283808b3fbdf12e9bea05fefca271d.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/5db407794669215f0f2b44d3c43440b3b0f9f0e99f788be62f9389c86d02dc38.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/57a82819b7cc52d39703ec91a6f1a83bc3ed87de6a98a2a19999066d7552f72e.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/b2230557346940d6b23d2c3c8cf4f257300156a8fdcb33de917d7c6281598880.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/05615ebf25d05bb37d830395423ddd29d64fce07302effbbff422a360730cbd0.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/2b1394982432822a6328ee7cdecb609b5b9ccb4cf9b66893ecbdb3b4eb7d0aa9.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/704433b0bda358b4b6d4f0b2ba72f474014e1570ded4bc44e56821ac1765ad8c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/addd02c234e94611af1c6552ebf693efc7c633a104b6a34d797a44e637fb8fe6.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/745e6382cef9ccfec1963862bcf0e003991492e9d34210862fec4979b0e37a52.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/11b0a68507b2211c4d237a0e7f50add0115b16e6dbd78030d7e3e3f4c19641fa.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/f952ab0219b9b90657e3b9b07f27af343524f34a5267cc64e9747d76115322f7.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/c32eb553e19d3c902b3b065d05cd69c135de68c699da016f5c8a0b4925530ead.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/3dc5b33edf9f79dfb249d3c1b552504967c9c5c534538eaa832d00093b19bd0c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ae0f5420802637138eaa3e72470dfe8bd2d670053e074b56b351439b946379c1.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/e8ef0e338deccfdbe6fb0b11dbe78fe7cc305512cb8937aa4425d1546b1d6f64.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/4fd13dc2c9f494620b2c9538cd8704f25a025472bf44ca041854db2dd7b789c7.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ed42f96b3639546ad215b798c3c65d6f67d6abcc7fe4c03532ab99cb5bcdd385.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/5cf20c5cf9a56fb93edfb9ab5a61e243bf50ee2fd62beb0b8d6f36b66509fef9.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/a12f25a01253108989eb986159962003eb0319f61e8f77fe3b2d76993068e1b2.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/1d4dc9f9fff32ae1743636a7cadc078d27e80e3b37020e793552923be7fef600.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-nutrients--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/8d16ffed42f516e920ec55ec90e88e0e701a3ba540f5475e9a9cd7acc41093cf.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-nutrients--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/fbc177801cfc3d4f33193e072e8b4a00ef953e95dcb956eb97bf2ee6522c6465.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-nutrients--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/c69d80eadc569e98c3447f7c81083f74866fc32f5cc2b8676515dcd844c316f8.png) |
</details>



<details>
<summary>🟡 storybook/widgets-meal-nutrients--default__[w900px] (cli [...]

2023-08-22 15:28 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2023-08-22 16:20 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2023-08-23 06:22 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 332       | 🟡       |
| Deleted         | 67     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 storybook/components-badge--all-states__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dea13e5c593e1a90c1759f8ecaf10b6c017b14e507a0422e0f122eb0dfc07c5c.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8b696718c79554103bca8de05c7a6d1015027c3b6d269813fa7fec913d48ff6e.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/029bc7108c40f833d3d78548eea1c4164d9fcdeaba58c5ddf4f7b4b5b8f6e3de.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dfe4ec2afb1ed1902a16cc2b087bd5de6fad1b35ae8d6eee768565c0ca2ccd90.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/11a51c87621aa923dc73e620d187a1f7dc7862dc315eb60c82c7efb81da90521.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1e7ae0e871ec9854e82b28b8dd2d2dbd25f597b6982ab5a8bc14607b72847fe7.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e53b26b7e5c0de6dacf7d330bc50c7375ac2960c361981ade0e1304e8cd760b6.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/77f06365fd72e7b85652aed060d8602b18ebc67ccf821f035aa76f7ffbf26cbe.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/7aba7db1dbefe46796980d8f718e6bea9c4237a8dc06ee71984431800398064c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5968e6a597503cbb177d052b2f065263282332e8251c8663694e900498918336.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1ac83021779e4c153b77f8ca5dd7939da55772a60d4f11cceb4dd6f15f599dca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e839dc541b4ce9c373b891275614436b21e7b1bc1ae35bea2e8cf39d281f3ba7.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3f1f35e34c5f80f8d005ffecd433a6f8b6de281daf3ad99b22bd931f4ab1503f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b43bcbba8f2e53f6176e263c503c448ce6fcd21dcf29bec7073ac7d8cb746298.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c49830474274889076bcd7e9dfc4b4add919cdf8c1443055af6db2b3ba8b946c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/ce09f0107914e2bafb4a82a9b6e9915e7ac94c9625e04a02fbcc53219ed770c0.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/98d9ddd4368146d21c791bca1020b32c8d369244d3c34f8fdf9f36047a340700.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3b1d0557477ab9e38b391ccb9cf24e2ed5bd6bd9049aca99c820c8e685888c71.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/fad419a34aa3a1fa18d689ddb55ad02f6602dc7f03b7c35e391e2f8491f6c5ca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d16653698068f9d3c28ea4295fe5569b598ebde3a2e9cfc7b47765a824f1faf6.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/33e6db51c7c7a961958186128f10c7eedaa354c3bf90d005abd9e53686508f7f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dc28afd48376cd64fe9fe85a953f5a53dca742730caa2d447cb8266cf1264318.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5c6c61af89d6fac785ce48a4658617e234a9e84faebdaa94d8d8b891364b0e93.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/81c71a755ffd16e4bc67911eb880c48f2285d117e973f9865bb3f7d4a02a5c79.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dada1a81bd4f99e5950ffe22115fdad9c40cc164207c8d2adc04ff31abb8f025.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c406967a4bb1016152b592443c1323bf8fa07c9b3df38d1a84861fa230fe6211.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/36f72ca78c9b76d12d07fbfafa77d3593c4219712a1846e0f7d5c2bb673804ce.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w900px] (click to expand)</summary> [...]

2023-08-23 08:38 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 332       | 🟡       |
| Deleted         | 67     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 storybook/components-badge--all-states__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dea13e5c593e1a90c1759f8ecaf10b6c017b14e507a0422e0f122eb0dfc07c5c.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8b696718c79554103bca8de05c7a6d1015027c3b6d269813fa7fec913d48ff6e.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/029bc7108c40f833d3d78548eea1c4164d9fcdeaba58c5ddf4f7b4b5b8f6e3de.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dfe4ec2afb1ed1902a16cc2b087bd5de6fad1b35ae8d6eee768565c0ca2ccd90.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/11a51c87621aa923dc73e620d187a1f7dc7862dc315eb60c82c7efb81da90521.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1e7ae0e871ec9854e82b28b8dd2d2dbd25f597b6982ab5a8bc14607b72847fe7.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e53b26b7e5c0de6dacf7d330bc50c7375ac2960c361981ade0e1304e8cd760b6.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/77f06365fd72e7b85652aed060d8602b18ebc67ccf821f035aa76f7ffbf26cbe.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/7aba7db1dbefe46796980d8f718e6bea9c4237a8dc06ee71984431800398064c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5968e6a597503cbb177d052b2f065263282332e8251c8663694e900498918336.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1ac83021779e4c153b77f8ca5dd7939da55772a60d4f11cceb4dd6f15f599dca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e839dc541b4ce9c373b891275614436b21e7b1bc1ae35bea2e8cf39d281f3ba7.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3f1f35e34c5f80f8d005ffecd433a6f8b6de281daf3ad99b22bd931f4ab1503f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b43bcbba8f2e53f6176e263c503c448ce6fcd21dcf29bec7073ac7d8cb746298.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c49830474274889076bcd7e9dfc4b4add919cdf8c1443055af6db2b3ba8b946c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/ce09f0107914e2bafb4a82a9b6e9915e7ac94c9625e04a02fbcc53219ed770c0.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/98d9ddd4368146d21c791bca1020b32c8d369244d3c34f8fdf9f36047a340700.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3b1d0557477ab9e38b391ccb9cf24e2ed5bd6bd9049aca99c820c8e685888c71.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/fad419a34aa3a1fa18d689ddb55ad02f6602dc7f03b7c35e391e2f8491f6c5ca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d16653698068f9d3c28ea4295fe5569b598ebde3a2e9cfc7b47765a824f1faf6.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/33e6db51c7c7a961958186128f10c7eedaa354c3bf90d005abd9e53686508f7f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dc28afd48376cd64fe9fe85a953f5a53dca742730caa2d447cb8266cf1264318.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5c6c61af89d6fac785ce48a4658617e234a9e84faebdaa94d8d8b891364b0e93.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/81c71a755ffd16e4bc67911eb880c48f2285d117e973f9865bb3f7d4a02a5c79.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dada1a81bd4f99e5950ffe22115fdad9c40cc164207c8d2adc04ff31abb8f025.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c406967a4bb1016152b592443c1323bf8fa07c9b3df38d1a84861fa230fe6211.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/36f72ca78c9b76d12d07fbfafa77d3593c4219712a1846e0f7d5c2bb673804ce.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w900px] (click to expand)</summary> [...]

2023-08-24 11:44 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 332       | 🟡       |
| Deleted         | 67     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 storybook/components-badge--all-states__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dea13e5c593e1a90c1759f8ecaf10b6c017b14e507a0422e0f122eb0dfc07c5c.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8b696718c79554103bca8de05c7a6d1015027c3b6d269813fa7fec913d48ff6e.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/029bc7108c40f833d3d78548eea1c4164d9fcdeaba58c5ddf4f7b4b5b8f6e3de.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dfe4ec2afb1ed1902a16cc2b087bd5de6fad1b35ae8d6eee768565c0ca2ccd90.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/11a51c87621aa923dc73e620d187a1f7dc7862dc315eb60c82c7efb81da90521.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1e7ae0e871ec9854e82b28b8dd2d2dbd25f597b6982ab5a8bc14607b72847fe7.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e53b26b7e5c0de6dacf7d330bc50c7375ac2960c361981ade0e1304e8cd760b6.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/77f06365fd72e7b85652aed060d8602b18ebc67ccf821f035aa76f7ffbf26cbe.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/7aba7db1dbefe46796980d8f718e6bea9c4237a8dc06ee71984431800398064c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5968e6a597503cbb177d052b2f065263282332e8251c8663694e900498918336.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1ac83021779e4c153b77f8ca5dd7939da55772a60d4f11cceb4dd6f15f599dca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e839dc541b4ce9c373b891275614436b21e7b1bc1ae35bea2e8cf39d281f3ba7.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3f1f35e34c5f80f8d005ffecd433a6f8b6de281daf3ad99b22bd931f4ab1503f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b43bcbba8f2e53f6176e263c503c448ce6fcd21dcf29bec7073ac7d8cb746298.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c49830474274889076bcd7e9dfc4b4add919cdf8c1443055af6db2b3ba8b946c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/ce09f0107914e2bafb4a82a9b6e9915e7ac94c9625e04a02fbcc53219ed770c0.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/98d9ddd4368146d21c791bca1020b32c8d369244d3c34f8fdf9f36047a340700.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3b1d0557477ab9e38b391ccb9cf24e2ed5bd6bd9049aca99c820c8e685888c71.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/fad419a34aa3a1fa18d689ddb55ad02f6602dc7f03b7c35e391e2f8491f6c5ca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d16653698068f9d3c28ea4295fe5569b598ebde3a2e9cfc7b47765a824f1faf6.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/33e6db51c7c7a961958186128f10c7eedaa354c3bf90d005abd9e53686508f7f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dc28afd48376cd64fe9fe85a953f5a53dca742730caa2d447cb8266cf1264318.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5c6c61af89d6fac785ce48a4658617e234a9e84faebdaa94d8d8b891364b0e93.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/81c71a755ffd16e4bc67911eb880c48f2285d117e973f9865bb3f7d4a02a5c79.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dada1a81bd4f99e5950ffe22115fdad9c40cc164207c8d2adc04ff31abb8f025.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c406967a4bb1016152b592443c1323bf8fa07c9b3df38d1a84861fa230fe6211.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/36f72ca78c9b76d12d07fbfafa77d3593c4219712a1846e0f7d5c2bb673804ce.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w900px] (click to expand)</summary> [...]

2023-08-24 12:02 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 332       | 🟡       |
| Deleted         | 67     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 storybook/components-badge--all-states__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dea13e5c593e1a90c1759f8ecaf10b6c017b14e507a0422e0f122eb0dfc07c5c.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8b696718c79554103bca8de05c7a6d1015027c3b6d269813fa7fec913d48ff6e.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/029bc7108c40f833d3d78548eea1c4164d9fcdeaba58c5ddf4f7b4b5b8f6e3de.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dfe4ec2afb1ed1902a16cc2b087bd5de6fad1b35ae8d6eee768565c0ca2ccd90.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/11a51c87621aa923dc73e620d187a1f7dc7862dc315eb60c82c7efb81da90521.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1e7ae0e871ec9854e82b28b8dd2d2dbd25f597b6982ab5a8bc14607b72847fe7.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e53b26b7e5c0de6dacf7d330bc50c7375ac2960c361981ade0e1304e8cd760b6.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/77f06365fd72e7b85652aed060d8602b18ebc67ccf821f035aa76f7ffbf26cbe.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/7aba7db1dbefe46796980d8f718e6bea9c4237a8dc06ee71984431800398064c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5968e6a597503cbb177d052b2f065263282332e8251c8663694e900498918336.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1ac83021779e4c153b77f8ca5dd7939da55772a60d4f11cceb4dd6f15f599dca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e839dc541b4ce9c373b891275614436b21e7b1bc1ae35bea2e8cf39d281f3ba7.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3f1f35e34c5f80f8d005ffecd433a6f8b6de281daf3ad99b22bd931f4ab1503f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b43bcbba8f2e53f6176e263c503c448ce6fcd21dcf29bec7073ac7d8cb746298.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c49830474274889076bcd7e9dfc4b4add919cdf8c1443055af6db2b3ba8b946c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/ce09f0107914e2bafb4a82a9b6e9915e7ac94c9625e04a02fbcc53219ed770c0.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/98d9ddd4368146d21c791bca1020b32c8d369244d3c34f8fdf9f36047a340700.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3b1d0557477ab9e38b391ccb9cf24e2ed5bd6bd9049aca99c820c8e685888c71.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/fad419a34aa3a1fa18d689ddb55ad02f6602dc7f03b7c35e391e2f8491f6c5ca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d16653698068f9d3c28ea4295fe5569b598ebde3a2e9cfc7b47765a824f1faf6.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/33e6db51c7c7a961958186128f10c7eedaa354c3bf90d005abd9e53686508f7f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dc28afd48376cd64fe9fe85a953f5a53dca742730caa2d447cb8266cf1264318.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5c6c61af89d6fac785ce48a4658617e234a9e84faebdaa94d8d8b891364b0e93.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/81c71a755ffd16e4bc67911eb880c48f2285d117e973f9865bb3f7d4a02a5c79.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dada1a81bd4f99e5950ffe22115fdad9c40cc164207c8d2adc04ff31abb8f025.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c406967a4bb1016152b592443c1323bf8fa07c9b3df38d1a84861fa230fe6211.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/36f72ca78c9b76d12d07fbfafa77d3593c4219712a1846e0f7d5c2bb673804ce.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w900px] (click to expand)</summary> [...]

2023-08-24 12:27 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 332       | 🟡       |
| Deleted         | 67     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 storybook/components-badge--all-states__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dea13e5c593e1a90c1759f8ecaf10b6c017b14e507a0422e0f122eb0dfc07c5c.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8b696718c79554103bca8de05c7a6d1015027c3b6d269813fa7fec913d48ff6e.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/029bc7108c40f833d3d78548eea1c4164d9fcdeaba58c5ddf4f7b4b5b8f6e3de.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dfe4ec2afb1ed1902a16cc2b087bd5de6fad1b35ae8d6eee768565c0ca2ccd90.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/11a51c87621aa923dc73e620d187a1f7dc7862dc315eb60c82c7efb81da90521.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1e7ae0e871ec9854e82b28b8dd2d2dbd25f597b6982ab5a8bc14607b72847fe7.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e53b26b7e5c0de6dacf7d330bc50c7375ac2960c361981ade0e1304e8cd760b6.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/77f06365fd72e7b85652aed060d8602b18ebc67ccf821f035aa76f7ffbf26cbe.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/7aba7db1dbefe46796980d8f718e6bea9c4237a8dc06ee71984431800398064c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5968e6a597503cbb177d052b2f065263282332e8251c8663694e900498918336.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1ac83021779e4c153b77f8ca5dd7939da55772a60d4f11cceb4dd6f15f599dca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e839dc541b4ce9c373b891275614436b21e7b1bc1ae35bea2e8cf39d281f3ba7.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3f1f35e34c5f80f8d005ffecd433a6f8b6de281daf3ad99b22bd931f4ab1503f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b43bcbba8f2e53f6176e263c503c448ce6fcd21dcf29bec7073ac7d8cb746298.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c49830474274889076bcd7e9dfc4b4add919cdf8c1443055af6db2b3ba8b946c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/ce09f0107914e2bafb4a82a9b6e9915e7ac94c9625e04a02fbcc53219ed770c0.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/98d9ddd4368146d21c791bca1020b32c8d369244d3c34f8fdf9f36047a340700.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3b1d0557477ab9e38b391ccb9cf24e2ed5bd6bd9049aca99c820c8e685888c71.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/fad419a34aa3a1fa18d689ddb55ad02f6602dc7f03b7c35e391e2f8491f6c5ca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d16653698068f9d3c28ea4295fe5569b598ebde3a2e9cfc7b47765a824f1faf6.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/33e6db51c7c7a961958186128f10c7eedaa354c3bf90d005abd9e53686508f7f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dc28afd48376cd64fe9fe85a953f5a53dca742730caa2d447cb8266cf1264318.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5c6c61af89d6fac785ce48a4658617e234a9e84faebdaa94d8d8b891364b0e93.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/81c71a755ffd16e4bc67911eb880c48f2285d117e973f9865bb3f7d4a02a5c79.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dada1a81bd4f99e5950ffe22115fdad9c40cc164207c8d2adc04ff31abb8f025.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c406967a4bb1016152b592443c1323bf8fa07c9b3df38d1a84861fa230fe6211.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/36f72ca78c9b76d12d07fbfafa77d3593c4219712a1846e0f7d5c2bb673804ce.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w900px] (click to expand)</summary> [...]

2023-08-24 12:29 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 68       | 🟡       |
| Deleted         | 13     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 custom/HeartRateDefault__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/034bff7f25790862bf65293233ed4735b623d26434be7fb07eb3443532121ee4.png) |
</details>



<details>
<summary>🟡 custom/HeartRateDefault__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/f37d6399af930abe37247d67307c4643af4e04c2ae6783b9af6962e5660ed6ea.png) |
</details>



<details>
<summary>🟡 custom/HeartRateDefault__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/be4a4862e7f2addf94689fde18a25fc1c682381734eee5ebc35947abd0df8cc3.png) |
</details>



<details>
<summary>🟡 custom/HeartRateDefault__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/f946447c52e94e95266d99ddf7027e63e5d9a1c70bbd394fa2beeb1a84377b54.png) |
</details>



<details>
<summary>🟡 custom/HeartRateHint__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ce6c63202f35d8d5a549b383b44a7b781f77fa7515bcf7ce17d251da3eaf645a.png) |
</details>



<details>
<summary>🟡 custom/HeartRateHint__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/6ed08517ebea5d1e2aa1563a38b5286f4fdcb8c372b4d8b1250f9cc97c315c51.png) |
</details>



<details>
<summary>🟡 custom/HeartRateHint__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/9e05311a37870ef3c3ceb88f24c1f37884b678ee3f2e6f137097682aafe69c40.png) |
</details>



<details>
<summary>🟡 custom/HeartRateHint__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/0fc6324e56c22be24fb985bb3de40380e45019ed3f0a0ba6c154fb4eb3fe0f8b.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/364f8a3bc78d2018533fbc3bd185e75161a2156d4608e3e8e7c392660767e033.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/a16913294cb25ddef1b768569113e32b9d6177378994a97ad73e4ce28d68569c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/eacc0afb719bda9fdd825b393028b4aad98ada9e6fc19247d1ae8ae89a7adbc0.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/9eb25204ce92c443fc34696414dd9c98aa12f32f6cdcd0aab8d2b6e7f16ce15d.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ade614c1048e433ce8bfed2767e6184b0b283808b3fbdf12e9bea05fefca271d.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/5db407794669215f0f2b44d3c43440b3b0f9f0e99f788be62f9389c86d02dc38.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/57a82819b7cc52d39703ec91a6f1a83bc3ed87de6a98a2a19999066d7552f72e.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/b2230557346940d6b23d2c3c8cf4f257300156a8fdcb33de917d7c6281598880.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/05615ebf25d05bb37d830395423ddd29d64fce07302effbbff422a360730cbd0.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/2b1394982432822a6328ee7cdecb609b5b9ccb4cf9b66893ecbdb3b4eb7d0aa9.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/704433b0bda358b4b6d4f0b2ba72f474014e1570ded4bc44e56821ac1765ad8c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/addd02c234e94611af1c6552ebf693efc7c633a104b6a34d797a44e637fb8fe6.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/745e6382cef9ccfec1963862bcf0e003991492e9d34210862fec4979b0e37a52.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/11b0a68507b2211c4d237a0e7f50add0115b16e6dbd78030d7e3e3f4c19641fa.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/f952ab0219b9b90657e3b9b07f27af343524f34a5267cc64e9747d76115322f7.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/c32eb553e19d3c902b3b065d05cd69c135de68c699da016f5c8a0b4925530ead.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/3dc5b33edf9f79dfb249d3c1b552504967c9c5c534538eaa832d00093b19bd0c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ae0f5420802637138eaa3e72470dfe8bd2d670053e074b56b351439b946379c1.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/e8ef0e338deccfdbe6fb0b11dbe78fe7cc305512cb8937aa4425d1546b1d6f64.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/4fd13dc2c9f494620b2c9538cd [...]

2023-08-24 12:46 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 332       | 🟡       |
| Deleted         | 67     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 storybook/components-badge--all-states__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dea13e5c593e1a90c1759f8ecaf10b6c017b14e507a0422e0f122eb0dfc07c5c.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8b696718c79554103bca8de05c7a6d1015027c3b6d269813fa7fec913d48ff6e.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/029bc7108c40f833d3d78548eea1c4164d9fcdeaba58c5ddf4f7b4b5b8f6e3de.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dfe4ec2afb1ed1902a16cc2b087bd5de6fad1b35ae8d6eee768565c0ca2ccd90.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/11a51c87621aa923dc73e620d187a1f7dc7862dc315eb60c82c7efb81da90521.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1e7ae0e871ec9854e82b28b8dd2d2dbd25f597b6982ab5a8bc14607b72847fe7.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e53b26b7e5c0de6dacf7d330bc50c7375ac2960c361981ade0e1304e8cd760b6.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/77f06365fd72e7b85652aed060d8602b18ebc67ccf821f035aa76f7ffbf26cbe.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/7aba7db1dbefe46796980d8f718e6bea9c4237a8dc06ee71984431800398064c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5968e6a597503cbb177d052b2f065263282332e8251c8663694e900498918336.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1ac83021779e4c153b77f8ca5dd7939da55772a60d4f11cceb4dd6f15f599dca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e839dc541b4ce9c373b891275614436b21e7b1bc1ae35bea2e8cf39d281f3ba7.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3f1f35e34c5f80f8d005ffecd433a6f8b6de281daf3ad99b22bd931f4ab1503f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b43bcbba8f2e53f6176e263c503c448ce6fcd21dcf29bec7073ac7d8cb746298.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c49830474274889076bcd7e9dfc4b4add919cdf8c1443055af6db2b3ba8b946c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/ce09f0107914e2bafb4a82a9b6e9915e7ac94c9625e04a02fbcc53219ed770c0.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/98d9ddd4368146d21c791bca1020b32c8d369244d3c34f8fdf9f36047a340700.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3b1d0557477ab9e38b391ccb9cf24e2ed5bd6bd9049aca99c820c8e685888c71.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/fad419a34aa3a1fa18d689ddb55ad02f6602dc7f03b7c35e391e2f8491f6c5ca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d16653698068f9d3c28ea4295fe5569b598ebde3a2e9cfc7b47765a824f1faf6.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/33e6db51c7c7a961958186128f10c7eedaa354c3bf90d005abd9e53686508f7f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dc28afd48376cd64fe9fe85a953f5a53dca742730caa2d447cb8266cf1264318.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5c6c61af89d6fac785ce48a4658617e234a9e84faebdaa94d8d8b891364b0e93.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/81c71a755ffd16e4bc67911eb880c48f2285d117e973f9865bb3f7d4a02a5c79.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dada1a81bd4f99e5950ffe22115fdad9c40cc164207c8d2adc04ff31abb8f025.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c406967a4bb1016152b592443c1323bf8fa07c9b3df38d1a84861fa230fe6211.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/36f72ca78c9b76d12d07fbfafa77d3593c4219712a1846e0f7d5c2bb673804ce.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w900px] (click to expand)</summary> [...]

2023-08-24 12:48 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 68       | 🟡       |
| Deleted         | 13     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 custom/HeartRateDefault__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/bcdebcedd70c62b677edd59fe3ce3c9e023e8659d6ca609ba1be47cc781958a4.png) |
</details>



<details>
<summary>🟡 custom/HeartRateDefault__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/4e046cbbdd94e0d427e1a6a04bd8662b9afbe6fd9110f88a2977677e783fdfe6.png) |
</details>



<details>
<summary>🟡 custom/HeartRateDefault__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/be4a4862e7f2addf94689fde18a25fc1c682381734eee5ebc35947abd0df8cc3.png) |
</details>



<details>
<summary>🟡 custom/HeartRateDefault__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/8792cce38c2d17199e53319603fe510fb0d6da9b77c9f7af59c343ceac2edf56.png) |
</details>



<details>
<summary>🟡 custom/HeartRateHint__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/52d43ecabafeef6913c2732d1f1bb81e7615035f6cdcd21c6fca1542361580a9.png) |
</details>



<details>
<summary>🟡 custom/HeartRateHint__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/6ed08517ebea5d1e2aa1563a38b5286f4fdcb8c372b4d8b1250f9cc97c315c51.png) |
</details>



<details>
<summary>🟡 custom/HeartRateHint__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/9e05311a37870ef3c3ceb88f24c1f37884b678ee3f2e6f137097682aafe69c40.png) |
</details>



<details>
<summary>🟡 custom/HeartRateHint__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/0fc6324e56c22be24fb985bb3de40380e45019ed3f0a0ba6c154fb4eb3fe0f8b.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/364f8a3bc78d2018533fbc3bd185e75161a2156d4608e3e8e7c392660767e033.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/a16913294cb25ddef1b768569113e32b9d6177378994a97ad73e4ce28d68569c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/eacc0afb719bda9fdd825b393028b4aad98ada9e6fc19247d1ae8ae89a7adbc0.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/9eb25204ce92c443fc34696414dd9c98aa12f32f6cdcd0aab8d2b6e7f16ce15d.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ade614c1048e433ce8bfed2767e6184b0b283808b3fbdf12e9bea05fefca271d.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/5db407794669215f0f2b44d3c43440b3b0f9f0e99f788be62f9389c86d02dc38.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/57a82819b7cc52d39703ec91a6f1a83bc3ed87de6a98a2a19999066d7552f72e.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/b2230557346940d6b23d2c3c8cf4f257300156a8fdcb33de917d7c6281598880.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/05615ebf25d05bb37d830395423ddd29d64fce07302effbbff422a360730cbd0.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/2b1394982432822a6328ee7cdecb609b5b9ccb4cf9b66893ecbdb3b4eb7d0aa9.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/704433b0bda358b4b6d4f0b2ba72f474014e1570ded4bc44e56821ac1765ad8c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/addd02c234e94611af1c6552ebf693efc7c633a104b6a34d797a44e637fb8fe6.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/745e6382cef9ccfec1963862bcf0e003991492e9d34210862fec4979b0e37a52.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/11b0a68507b2211c4d237a0e7f50add0115b16e6dbd78030d7e3e3f4c19641fa.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/f952ab0219b9b90657e3b9b07f27af343524f34a5267cc64e9747d76115322f7.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/c32eb553e19d3c902b3b065d05cd69c135de68c699da016f5c8a0b4925530ead.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/3dc5b33edf9f79dfb249d3c1b552504967c9c5c534538eaa832d00093b19bd0c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ae0f5420802637138eaa3e72470dfe8bd2d670053e074b56b351439b946379c1.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/e8ef0e338deccfdbe6fb0b11dbe78fe7cc305512cb8937aa4425d1546b1d6f64.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/4fd13dc2c9f494620b2c9538cd [...]

2023-08-24 13:03 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 332       | 🟡       |
| Deleted         | 67     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 storybook/components-badge--all-states__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dea13e5c593e1a90c1759f8ecaf10b6c017b14e507a0422e0f122eb0dfc07c5c.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8b696718c79554103bca8de05c7a6d1015027c3b6d269813fa7fec913d48ff6e.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/029bc7108c40f833d3d78548eea1c4164d9fcdeaba58c5ddf4f7b4b5b8f6e3de.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dfe4ec2afb1ed1902a16cc2b087bd5de6fad1b35ae8d6eee768565c0ca2ccd90.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/11a51c87621aa923dc73e620d187a1f7dc7862dc315eb60c82c7efb81da90521.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1e7ae0e871ec9854e82b28b8dd2d2dbd25f597b6982ab5a8bc14607b72847fe7.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e53b26b7e5c0de6dacf7d330bc50c7375ac2960c361981ade0e1304e8cd760b6.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/77f06365fd72e7b85652aed060d8602b18ebc67ccf821f035aa76f7ffbf26cbe.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/7aba7db1dbefe46796980d8f718e6bea9c4237a8dc06ee71984431800398064c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5968e6a597503cbb177d052b2f065263282332e8251c8663694e900498918336.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1ac83021779e4c153b77f8ca5dd7939da55772a60d4f11cceb4dd6f15f599dca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e839dc541b4ce9c373b891275614436b21e7b1bc1ae35bea2e8cf39d281f3ba7.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3f1f35e34c5f80f8d005ffecd433a6f8b6de281daf3ad99b22bd931f4ab1503f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b43bcbba8f2e53f6176e263c503c448ce6fcd21dcf29bec7073ac7d8cb746298.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c49830474274889076bcd7e9dfc4b4add919cdf8c1443055af6db2b3ba8b946c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/ce09f0107914e2bafb4a82a9b6e9915e7ac94c9625e04a02fbcc53219ed770c0.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/98d9ddd4368146d21c791bca1020b32c8d369244d3c34f8fdf9f36047a340700.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3b1d0557477ab9e38b391ccb9cf24e2ed5bd6bd9049aca99c820c8e685888c71.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/fad419a34aa3a1fa18d689ddb55ad02f6602dc7f03b7c35e391e2f8491f6c5ca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d16653698068f9d3c28ea4295fe5569b598ebde3a2e9cfc7b47765a824f1faf6.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/33e6db51c7c7a961958186128f10c7eedaa354c3bf90d005abd9e53686508f7f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dc28afd48376cd64fe9fe85a953f5a53dca742730caa2d447cb8266cf1264318.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5c6c61af89d6fac785ce48a4658617e234a9e84faebdaa94d8d8b891364b0e93.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/81c71a755ffd16e4bc67911eb880c48f2285d117e973f9865bb3f7d4a02a5c79.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dada1a81bd4f99e5950ffe22115fdad9c40cc164207c8d2adc04ff31abb8f025.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c406967a4bb1016152b592443c1323bf8fa07c9b3df38d1a84861fa230fe6211.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/36f72ca78c9b76d12d07fbfafa77d3593c4219712a1846e0f7d5c2bb673804ce.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w900px] (click to expand)</summary> [...]

2023-08-24 13:05 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 64       | 🟡       |
| Deleted         | 13     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 custom/widgets-heart-rate--hint-opened__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/efd85ded3eb74fa875309c9e2f6e40ab6f6af884293194a123b4486dfadb3b72.png) |
</details>



<details>
<summary>🟡 custom/widgets-heart-rate--hint-opened__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/10c4344eae53c06a89e945bbaf1437d74d26c6cc877af502588e0e376b6deb18.png) |
</details>



<details>
<summary>🟡 custom/widgets-heart-rate--hint-opened__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/0c1990617e3260b778535c9e3883483fd5c4905fe68ad58f5d732218e04cdb19.png) |
</details>



<details>
<summary>🟡 custom/widgets-heart-rate--hint-opened__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/7ab0f339a84906674738429b4b91e6db1dbd24b026df961a529ba41a1f7ef2d4.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/364f8a3bc78d2018533fbc3bd185e75161a2156d4608e3e8e7c392660767e033.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/a16913294cb25ddef1b768569113e32b9d6177378994a97ad73e4ce28d68569c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/eacc0afb719bda9fdd825b393028b4aad98ada9e6fc19247d1ae8ae89a7adbc0.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/9eb25204ce92c443fc34696414dd9c98aa12f32f6cdcd0aab8d2b6e7f16ce15d.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ade614c1048e433ce8bfed2767e6184b0b283808b3fbdf12e9bea05fefca271d.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/5db407794669215f0f2b44d3c43440b3b0f9f0e99f788be62f9389c86d02dc38.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/57a82819b7cc52d39703ec91a6f1a83bc3ed87de6a98a2a19999066d7552f72e.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/b2230557346940d6b23d2c3c8cf4f257300156a8fdcb33de917d7c6281598880.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/05615ebf25d05bb37d830395423ddd29d64fce07302effbbff422a360730cbd0.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/2b1394982432822a6328ee7cdecb609b5b9ccb4cf9b66893ecbdb3b4eb7d0aa9.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/704433b0bda358b4b6d4f0b2ba72f474014e1570ded4bc44e56821ac1765ad8c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/addd02c234e94611af1c6552ebf693efc7c633a104b6a34d797a44e637fb8fe6.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/745e6382cef9ccfec1963862bcf0e003991492e9d34210862fec4979b0e37a52.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/11b0a68507b2211c4d237a0e7f50add0115b16e6dbd78030d7e3e3f4c19641fa.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/f952ab0219b9b90657e3b9b07f27af343524f34a5267cc64e9747d76115322f7.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/c32eb553e19d3c902b3b065d05cd69c135de68c699da016f5c8a0b4925530ead.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/3dc5b33edf9f79dfb249d3c1b552504967c9c5c534538eaa832d00093b19bd0c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ae0f5420802637138eaa3e72470dfe8bd2d670053e074b56b351439b946379c1.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/e8ef0e338deccfdbe6fb0b11dbe78fe7cc305512cb8937aa4425d1546b1d6f64.png) |
</details>



<details>
<summary>🟡 storybook/widgets-heart-rate--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/4fd13dc2c9f494620b2c9538cd8704f25a025472bf44ca041854db2dd7b789c7.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ed42f96b3639546ad215b798c3c65d6f67d6abcc7fe4c03532ab99cb5bcdd385.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/5cf20c5cf9a56fb93edfb9ab5a61e243bf50ee2fd62beb0b8d6f36b66509fef9.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/a12f25a01253108989eb986159962003eb0319f61e8f77fe3b2d76993068e1b2.png) |
</details>



<details>
<summary>🟡 storybook/widgets-list-goals--list-goals__[w900px] (click to expand [...]

2023-08-28 13:22 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 68       | 🟡       |
| Deleted         | 13     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 custom/widgets-heart-rate--hint-opened__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/2a40c7f270dfa1b98e95507152617c2c509593ae9783feefbc2a67bbe2f090ce.png) |
</details>



<details>
<summary>🟡 custom/widgets-heart-rate--hint-opened__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/090a00be38e6020d4ba55266740d4434ee2ff03349db392de021b368fcbc6e87.png) |
</details>



<details>
<summary>🟡 custom/widgets-heart-rate--hint-opened__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/247077aa579ffd8842445ee188fd017bd6f7d907ded6984592c52d445555fe6b.png) |
</details>



<details>
<summary>🟡 custom/widgets-heart-rate--hint-opened__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/7158963f507d526cef74ab8b0c06ff674eddb9f972a63289e53c652446009ef3.png) |
</details>



<details>
<summary>🟡 custom/widgets-meal-nutrients--hint-opened__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ff87bec8289ee23312b8fb3beaf1916597a8535fa46380170c83880abaad3918.png) |
</details>



<details>
<summary>🟡 custom/widgets-meal-nutrients--hint-opened__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/4f4e3b4d9eaa928ea8005260d253863ecfbbc5a20173b039002848a674591637.png) |
</details>



<details>
<summary>🟡 custom/widgets-meal-nutrients--hint-opened__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/6a6be42bedcc7136ce2f329f6f850fc57866ed13197f4ff5be2fc1607c45e0b7.png) |
</details>



<details>
<summary>🟡 custom/widgets-meal-nutrients--hint-opened__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/d2afd7d31327c2053e9088c9bc063b2ee3086e43180c6a2143ac7142d7303d1e.png) |
</details>



<details>
<summary>🟡 custom/widgets-navbar--mobile-opened__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/2e87ce22e0bfada893ed27fdacb07f85a67cb7e3dbc2e0e6d9864a5357b7a1d2.png) |
</details>



<details>
<summary>🟡 custom/widgets-navbar--mobile-opened__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/d36a9753e90ec9ef0c5bae3469c8368d255b5f6c454968f9074fe2c86243d9f0.png) |
</details>



<details>
<summary>🟡 custom/widgets-navbar--mobile-opened__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/e4caa8211a8ba2813d258804c76634aa3ca79b295a09a58f68008ddc8cf8049a.png) |
</details>



<details>
<summary>🟡 custom/widgets-navbar--mobile-opened__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/234a6883198e1bbf3c4dfb64959ec4ccffe1f1541fb9ff2b86cbd7463108c897.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/364f8a3bc78d2018533fbc3bd185e75161a2156d4608e3e8e7c392660767e033.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/a16913294cb25ddef1b768569113e32b9d6177378994a97ad73e4ce28d68569c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/eacc0afb719bda9fdd825b393028b4aad98ada9e6fc19247d1ae8ae89a7adbc0.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/9eb25204ce92c443fc34696414dd9c98aa12f32f6cdcd0aab8d2b6e7f16ce15d.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ade614c1048e433ce8bfed2767e6184b0b283808b3fbdf12e9bea05fefca271d.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/5db407794669215f0f2b44d3c43440b3b0f9f0e99f788be62f9389c86d02dc38.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/57a82819b7cc52d39703ec91a6f1a83bc3ed87de6a98a2a19999066d7552f72e.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/b2230557346940d6b23d2c3c8cf4f257300156a8fdcb33de917d7c6281598880.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/05615ebf25d05bb37d830395423ddd29d64fce07302effbbff422a360730cbd0.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/2b1394982432822a6328ee7cdecb609b5b9ccb4cf9b66893ecbdb3b4eb7d0aa9.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/704433b0bda358b4b6d4f0b2ba72f474014e1570ded4bc44e56821ac1765ad8c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/addd02c234e94611af1c6552ebf693efc7c633a104b6a34d797a44e637fb8fe6.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/745e6382cef9ccfec1963862bcf0e003991492e9d34210862fec4979b0e37a52.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/11b0a68507b2211c4d237a0e7f50add0115b16e6dbd78030d7e3e3f4c19641fa.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/f952ab0219b9b90657e3b9b07f27af343524f34a5267cc64e9747d76115322f7.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w900px] (click to ex [...]

2023-08-28 13:38 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 332       | 🟡       |
| Deleted         | 67     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 storybook/components-badge--all-states__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dea13e5c593e1a90c1759f8ecaf10b6c017b14e507a0422e0f122eb0dfc07c5c.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/8b696718c79554103bca8de05c7a6d1015027c3b6d269813fa7fec913d48ff6e.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/029bc7108c40f833d3d78548eea1c4164d9fcdeaba58c5ddf4f7b4b5b8f6e3de.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--all-states__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dfe4ec2afb1ed1902a16cc2b087bd5de6fad1b35ae8d6eee768565c0ca2ccd90.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/11a51c87621aa923dc73e620d187a1f7dc7862dc315eb60c82c7efb81da90521.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1e7ae0e871ec9854e82b28b8dd2d2dbd25f597b6982ab5a8bc14607b72847fe7.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e53b26b7e5c0de6dacf7d330bc50c7375ac2960c361981ade0e1304e8cd760b6.png) |
</details>



<details>
<summary>🟡 storybook/components-badge--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/77f06365fd72e7b85652aed060d8602b18ebc67ccf821f035aa76f7ffbf26cbe.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/7aba7db1dbefe46796980d8f718e6bea9c4237a8dc06ee71984431800398064c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5968e6a597503cbb177d052b2f065263282332e8251c8663694e900498918336.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/1ac83021779e4c153b77f8ca5dd7939da55772a60d4f11cceb4dd6f15f599dca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--block__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e839dc541b4ce9c373b891275614436b21e7b1bc1ae35bea2e8cf39d281f3ba7.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3f1f35e34c5f80f8d005ffecd433a6f8b6de281daf3ad99b22bd931f4ab1503f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b43bcbba8f2e53f6176e263c503c448ce6fcd21dcf29bec7073ac7d8cb746298.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c49830474274889076bcd7e9dfc4b4add919cdf8c1443055af6db2b3ba8b946c.png) |
</details>



<details>
<summary>🟡 storybook/components-button--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/ce09f0107914e2bafb4a82a9b6e9915e7ac94c9625e04a02fbcc53219ed770c0.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/98d9ddd4368146d21c791bca1020b32c8d369244d3c34f8fdf9f36047a340700.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3b1d0557477ab9e38b391ccb9cf24e2ed5bd6bd9049aca99c820c8e685888c71.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/fad419a34aa3a1fa18d689ddb55ad02f6602dc7f03b7c35e391e2f8491f6c5ca.png) |
</details>



<details>
<summary>🟡 storybook/components-button--end-icon__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/d16653698068f9d3c28ea4295fe5569b598ebde3a2e9cfc7b47765a824f1faf6.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/33e6db51c7c7a961958186128f10c7eedaa354c3bf90d005abd9e53686508f7f.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dc28afd48376cd64fe9fe85a953f5a53dca742730caa2d447cb8266cf1264318.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/5c6c61af89d6fac785ce48a4658617e234a9e84faebdaa94d8d8b891364b0e93.png) |
</details>



<details>
<summary>🟡 storybook/components-button--focused__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/81c71a755ffd16e4bc67911eb880c48f2285d117e973f9865bb3f7d4a02a5c79.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/dada1a81bd4f99e5950ffe22115fdad9c40cc164207c8d2adc04ff31abb8f025.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c406967a4bb1016152b592443c1323bf8fa07c9b3df38d1a84861fa230fe6211.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/36f72ca78c9b76d12d07fbfafa77d3593c4219712a1846e0f7d5c2bb673804ce.png) |
</details>



<details>
<summary>🟡 storybook/components-button--large__[w900px] (click to expand)</summary> [...]

2023-08-28 13:41 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 68       | 🟡       |
| Deleted         | 13     | ❌       |
| Regression      | 0  | ❗       |
    


<details>
<summary>🟡 custom/widgets-heart-rate--hint-opened__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/2a40c7f270dfa1b98e95507152617c2c509593ae9783feefbc2a67bbe2f090ce.png) |
</details>



<details>
<summary>🟡 custom/widgets-heart-rate--hint-opened__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/090a00be38e6020d4ba55266740d4434ee2ff03349db392de021b368fcbc6e87.png) |
</details>



<details>
<summary>🟡 custom/widgets-heart-rate--hint-opened__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/247077aa579ffd8842445ee188fd017bd6f7d907ded6984592c52d445555fe6b.png) |
</details>



<details>
<summary>🟡 custom/widgets-heart-rate--hint-opened__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/7158963f507d526cef74ab8b0c06ff674eddb9f972a63289e53c652446009ef3.png) |
</details>



<details>
<summary>🟡 custom/widgets-meal-nutrients--hint-opened__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/61a6c178d1297886504a5995e210721d2037b5bec6c62409b0e1009be83eb041.png) |
</details>



<details>
<summary>🟡 custom/widgets-meal-nutrients--hint-opened__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/4f4e3b4d9eaa928ea8005260d253863ecfbbc5a20173b039002848a674591637.png) |
</details>



<details>
<summary>🟡 custom/widgets-meal-nutrients--hint-opened__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/6a6be42bedcc7136ce2f329f6f850fc57866ed13197f4ff5be2fc1607c45e0b7.png) |
</details>



<details>
<summary>🟡 custom/widgets-meal-nutrients--hint-opened__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/02c44192a8a97f54729256851e65c79a7b8aa546f3e33d81e8f5454c0cfe3d0d.png) |
</details>



<details>
<summary>🟡 custom/widgets-navbar--mobile-opened__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/2e87ce22e0bfada893ed27fdacb07f85a67cb7e3dbc2e0e6d9864a5357b7a1d2.png) |
</details>



<details>
<summary>🟡 custom/widgets-navbar--mobile-opened__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/d36a9753e90ec9ef0c5bae3469c8368d255b5f6c454968f9074fe2c86243d9f0.png) |
</details>



<details>
<summary>🟡 custom/widgets-navbar--mobile-opened__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/e4caa8211a8ba2813d258804c76634aa3ca79b295a09a58f68008ddc8cf8049a.png) |
</details>



<details>
<summary>🟡 custom/widgets-navbar--mobile-opened__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/234a6883198e1bbf3c4dfb64959ec4ccffe1f1541fb9ff2b86cbd7463108c897.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/364f8a3bc78d2018533fbc3bd185e75161a2156d4608e3e8e7c392660767e033.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/a16913294cb25ddef1b768569113e32b9d6177378994a97ad73e4ce28d68569c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/eacc0afb719bda9fdd825b393028b4aad98ada9e6fc19247d1ae8ae89a7adbc0.png) |
</details>



<details>
<summary>🟡 storybook/widgets-activity--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/9eb25204ce92c443fc34696414dd9c98aa12f32f6cdcd0aab8d2b6e7f16ce15d.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/ade614c1048e433ce8bfed2767e6184b0b283808b3fbdf12e9bea05fefca271d.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/5db407794669215f0f2b44d3c43440b3b0f9f0e99f788be62f9389c86d02dc38.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/57a82819b7cc52d39703ec91a6f1a83bc3ed87de6a98a2a19999066d7552f72e.png) |
</details>



<details>
<summary>🟡 storybook/widgets-bmi--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/b2230557346940d6b23d2c3c8cf4f257300156a8fdcb33de917d7c6281598880.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/05615ebf25d05bb37d830395423ddd29d64fce07302effbbff422a360730cbd0.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/2b1394982432822a6328ee7cdecb609b5b9ccb4cf9b66893ecbdb3b4eb7d0aa9.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/704433b0bda358b4b6d4f0b2ba72f474014e1570ded4bc44e56821ac1765ad8c.png) |
</details>



<details>
<summary>🟡 storybook/widgets-calories--default__[w900px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/addd02c234e94611af1c6552ebf693efc7c633a104b6a34d797a44e637fb8fe6.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1440px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/745e6382cef9ccfec1963862bcf0e003991492e9d34210862fec4979b0e37a52.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w1920px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/11b0a68507b2211c4d237a0e7f50add0115b16e6dbd78030d7e3e3f4c19641fa.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w390px] (click to expand)</summary>

| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/f952ab0219b9b90657e3b9b07f27af343524f34a5267cc64e9747d76115322f7.png) |
</details>



<details>
<summary>🟡 storybook/widgets-card-list--card-list__[w900px] (click to ex [...]

2023-08-28 15:23 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2023-08-28 15:58 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ storybook/components-card--item-card__[w390px]*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/ef1f46a90870f5ef1f6157515e107ae591a751eec4b102c7de44ca92fed28444.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/0495e2cf8714e5b53db04d2ce4b5e6a6fd624e40d8f17237e79537b480c38494.png) |

2023-08-28 16:10 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 1  | ❗       |
    


*❗ storybook/components-card--item-card__[w1920px]*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b7e4f8f0634a597163c95b694e2dd8cde45877b247b586ee1f396948845bd8f6.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/770f342fe51b7b760e2ed8cda1f2602812bdd07358e5d52f82a7f609e733cab4.png) |

2023-08-28 16:13 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2023-08-28 16:16 UTC, arthur-kashaiev-ssa-group requested changes

2023-08-29 10:30 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 4       | 🟡       |
| Deleted         | 4     | ❌       |
| Regression      | 1  | ❗       |
    


*🟡 storybook/components-color-picker--selected-color__[w1440px]*: 


| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/df00f07a2dd183f1fc8b6fe6f65286a79849c7cd3cd52f7b6a01ea4e378a9cd3.png) |



*🟡 storybook/components-color-picker--selected-color__[w1920px]*: 


| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b9066d647a0740c1fb3da517aa40af3f68547a626d7cc6cbadc611e87abd93a7.png) |



*🟡 storybook/components-color-picker--selected-color__[w390px]*: 


| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/eb655efda2b1e7bcaac3d87b30fbaf2de88eff1663e795312f382d2890539620.png) |



*🟡 storybook/components-color-picker--selected-color__[w900px]*: 


| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/67fbbe8e932a9907a4329c2ef914a637ebe435f4bee12336c52dcb7e2f241f2f.png) |



*❌ storybook/components-color-picker--setted-color__[w1440px]*: 


| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/df00f07a2dd183f1fc8b6fe6f65286a79849c7cd3cd52f7b6a01ea4e378a9cd3.png) |



*❌ storybook/components-color-picker--setted-color__[w1920px]*: 


| Image |
| --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b9066d647a0740c1fb3da517aa40af3f68547a626d7cc6cbadc611e87abd93a7.png) |



*❌ storybook/components-color-picker--setted-color__[w390px]*: 


| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/eb655efda2b1e7bcaac3d87b30fbaf2de88eff1663e795312f382d2890539620.png) |



*❌ storybook/components-color-picker--setted-color__[w900px]*: 


| Image |
| --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/67fbbe8e932a9907a4329c2ef914a637ebe435f4bee12336c52dcb7e2f241f2f.png) |



*❗ storybook/components-card--item-card__[w1920px]*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/770f342fe51b7b760e2ed8cda1f2602812bdd07358e5d52f82a7f609e733cab4.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b7e4f8f0634a597163c95b694e2dd8cde45877b247b586ee1f396948845bd8f6.png) |

2023-08-29 10:32 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 5  | ❗       |
    


*❗ custom/widgets-heart-rate--hint-opened__[w1440px]*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/2a40c7f270dfa1b98e95507152617c2c509593ae9783feefbc2a67bbe2f090ce.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/17ff0bafc0097fe0631a16fc8be34784f6675e69dfb016e6092b07c5e9966c62.png) |



*❗ custom/widgets-heart-rate--hint-opened__[w1920px]*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/090a00be38e6020d4ba55266740d4434ee2ff03349db392de021b368fcbc6e87.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/3da1f51f8e833cb2bc7d76d2eb84944786d677913e87edf8ba35942188afbabc.png) |



*❗ custom/widgets-heart-rate--hint-opened__[w900px]*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/7158963f507d526cef74ab8b0c06ff674eddb9f972a63289e53c652446009ef3.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/697051d2a61ebb193adc44f5d6ee5e1258b373320411ed28b5b97b8f3078c52e.png) |



*❗ custom/widgets-meal-nutrients--hint-opened__[w1920px]*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/4f4e3b4d9eaa928ea8005260d253863ecfbbc5a20173b039002848a674591637.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/222ea8464c66431bd05bdbbabcb7fec72a248a7692904087b6dac20a36aec4ef.png) |



*❗ custom/widgets-navbar--mobile-opened__[w1920px]*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/d36a9753e90ec9ef0c5bae3469c8368d255b5f6c454968f9074fe2c86243d9f0.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/4effe7b4876f48bdeb4b5fce74c66cc43422610a74252d51ab2364cd8ebba55f.png) |

2023-08-29 10:38 UTC, react-developer-ssa-group commented on package.json
> +    "sb:dev:quite": "storybook dev -p 6001 --quite",
Done

2023-08-29 10:39 UTC, react-developer-ssa-group commented on packages/core/src/components/ColorPicker/ColorPicker.stories.tsx
> +export const SettedColor = () => {
Renamed

2023-08-29 10:39 UTC, react-developer-ssa-group commented on packages/widgets/.gitignore
> +node_modules/
Used only the root .gitignore file

2023-08-29 10:49 UTC, arthur-kashaiev-ssa-group approved these changes

2023-08-29 10:53 UTC, merged