Make TS-check more strict
ssagroup/ui-kit pull request #66
Opened 2023-09-08 15:26 UTC by react-developer-ssa-group

[Make TS-check more strict](https://github.com/ssagroup/ui-kit/issues/65)
- added detailed typing

Closes #65

2023-09-10 17:27 UTC, arthur-kashaiev-ssa-group requested changes
Looks good to me. I've just left one small comment.

2023-09-10 17:27 UTC, arthur-kashaiev-ssa-group commented on packages/core/src/components/Wrapper/Wrapper.tsx
> +import { CommonProps } from '../..';
I suggest using another way of import (throughout the project): 
`import { CommonProps } from '@types/emotion';`

I'm unsure whether the `'../..'` will work in all cases.

2023-09-10 18:45 UTC, arthur-kashaiev-ssa-group commented
@react-developer-ssa-group This is the commit you need to make the Button types work: 
https://github.com/ssagroup/ui-kit/commit/17340dee2a129070a1c6f3549e248fc4c2b94fef

2023-09-11 07:45 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 8  | ❗       |
    


<details>
<summary>❗ storybook/components-card--item-card__[w1440px] (click to expand)</summary>

| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/81fb20619ed37275a3053643f41d0cf65e2e38972bbf605549d83ef8da883214.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/3f917f6cd7fb30a5c5c4fc5043d4002aba1cabb9f1a50eabd4ff8291b894eb97.png) |
</details>



<details>
<summary>❗ storybook/components-card--item-card__[w1920px] (click to expand)</summary>

| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/770f342fe51b7b760e2ed8cda1f2602812bdd07358e5d52f82a7f609e733cab4.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/b7e4f8f0634a597163c95b694e2dd8cde45877b247b586ee1f396948845bd8f6.png) |
</details>



<details>
<summary>❗ storybook/components-card--item-card__[w390px] (click to expand)</summary>

| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/ef1f46a90870f5ef1f6157515e107ae591a751eec4b102c7de44ca92fed28444.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/0495e2cf8714e5b53db04d2ce4b5e6a6fd624e40d8f17237e79537b480c38494.png) |
</details>



<details>
<summary>❗ storybook/components-card--item-card-action__[w390px] (click to expand)</summary>

| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c6f13ff8aec706eced5cd92d71c2fdf5664dadaa20dc1b9ca976892d0784db25.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/e58dd19336d57d521afd4fd21c931b56fe8344e9250bc6ae5ba28b86f5c49929.png) |
</details>



<details>
<summary>❗ storybook/components-card--item-card-action__[w900px] (click to expand)</summary>

| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/6624d9cc0500953552dafa018e6cd5487a8ea1bf1ea50ce05ec6a6aa105d8a85.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/81f56f9b49a8584939f792baaa85270f5411f8be47524893e5e82b0aebea6450.png) |
</details>



<details>
<summary>❗ storybook/components-card--item-card-avatar__[w1440px] (click to expand)</summary>

| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/63b2ede3088d32dcfbc5764c35c03595c34f9f7d4fb388174dd461f0f6735854.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/c7d20fda6d7ba1cf7fc6d0f0a7f1fbb09fe1bd423d336a7c55d518df9ab25924.png) |
</details>



<details>
<summary>❗ storybook/components-card--item-card-avatar__[w1920px] (click to expand)</summary>

| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/bbac89b55b80f5eae8f92a579ea0f40cbfb7acaa37957b8e6c6771c096ebfbe4.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/fae0485fc44276f79e636b3cca4d4120db96996a5a75906521f9ae0e9673c7c2.png) |
</details>



<details>
<summary>❗ storybook/components-card--item-card-avatar__[w900px] (click to expand)</summary>

| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/290f31e960a4954710fe88cd15b36ff38d47c358238584595cab0410b71386e8.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrwk2t4dkena0e4nu2rikp/db98f95a058c7de452ddb58f4c20b37a9f86595f19cd85de6edc4b9f2312c2f3.png) |
</details>

2023-09-11 07:47 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 2  | ❗       |
    


*❗ custom/widgets-heart-rate--hint-opened__[w1920px]*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/c85b3c4ac3f696999d82456e97f2e957a0fb81893c7db4eb3c7c6821eeaee71f.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/3da1f51f8e833cb2bc7d76d2eb84944786d677913e87edf8ba35942188afbabc.png) |



*❗ custom/widgets-heart-rate--hint-opened__[w900px]*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/4f6bc66456a5849669c1e7ea795f6fb0942b30614b3f47658b287011b6c300b1.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/697051d2a61ebb193adc44f5d6ee5e1258b373320411ed28b5b97b8f3078c52e.png) |

2023-09-11 09:11 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 0  | ❗       |

2023-09-11 09:13 UTC, lost-pixel-signals commented
| Shot Type       | Count                | Status   |
| -------------   | -------------------- | -------- |
| Added           | 0       | 🟡       |
| Deleted         | 0     | ❌       |
| Regression      | 4  | ❗       |
    


*❗ custom/widgets-heart-rate--hint-opened__[w1440px]*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/17ff0bafc0097fe0631a16fc8be34784f6675e69dfb016e6092b07c5e9966c62.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/2a40c7f270dfa1b98e95507152617c2c509593ae9783feefbc2a67bbe2f090ce.png) |



*❗ custom/widgets-heart-rate--hint-opened__[w1920px]*: 


| Before | After |
| --- | --- |
| ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/3da1f51f8e833cb2bc7d76d2eb84944786d677913e87edf8ba35942188afbabc.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/c85b3c4ac3f696999d82456e97f2e957a0fb81893c7db4eb3c7c6821eeaee71f.png) |



*❗ custom/widgets-heart-rate--hint-opened__[w390px]*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/eacde3228764712a78fa5d19c35e9f43a90df96f5451c48eab7058ef4511b22a.png) | ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/6c2dd355da3e0b9c6004efb808409bbc0ca9d09aa828a20751ebd94a088cb10f.png) |



*❗ custom/widgets-heart-rate--hint-opened__[w900px]*: 


| Before | After |
| --- | --- |
| ![](https://lp-00002-d34ac.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/697051d2a61ebb193adc44f5d6ee5e1258b373320411ed28b5b97b8f3078c52e.png) | ![](https://lp-00001-a8c7a.fra1.digitaloceanspaces.com/clldrvzro4dkcna0ez80h1y2h/4f6bc66456a5849669c1e7ea795f6fb0942b30614b3f47658b287011b6c300b1.png) |

2023-09-11 10:35 UTC, arthur-kashaiev-ssa-group approved these changes

2023-09-11 11:14 UTC, merged